### ISSUE TITLE
500 errors when running subscriptions

### ISSUE THREAD

**Issue by thisbejim** [GetStream/stream-js#101]
Currently when running subscriptions I am getting some 500 errors when connecting to faye:

![image](https://cloud.githubusercontent.com/assets/10917363/22229704/7a1f6f2c-e22d-11e6-8fd6-279ea6cff7ea.png)

Sometimes it connects perfectly fine and sometimes I get the above error.

Here is a minimal repro: https://github.com/thisbejim/500-repro
There are missing credentials in the repro that are required to run Stream but I have written to Stream support with those missing details and have referenced this issue.

**Comment by tbarbugli** [comment]
handling this via support
