### ISSUE TITLE
Activity copy limit for followMany

### ISSUE THREAD

**Issue by rfrench** [GetStream/stream-js#102]
The falsy check on callbackOrActivityCopyLimit & activityCopyLimit for followMany fails with a value of 0. I can send a pull request if need be.

https://github.com/GetStream/stream-js/blob/master/src/lib/batch_operations.js#L40-L42
and
https://github.com/GetStream/stream-js/blob/master/src/lib/batch_operations.js#L48-L50

**Comment by tbarbugli** [comment]
good catch! we'll fix this, if you already have a patch ready feel free to create a PR
