### ISSUE TITLE
Error subclasses do not correctly extend Error

### ISSUE THREAD

**Issue by OliverJAsh** [GetStream/stream-js#119]
The way in which this package extends `Error` to create subclasses, [e.g. `FeedError`](https://github.com/GetStream/stream-js/blob/81aa083fb848b6fa3e07e9bdd4352bb2e41fa513/src/lib/errors.js#L13), means that these errors may not be detected as subclasses.

This matters because Sentry, the popular error reporting tool, will not detect this as an `Error`: https://github.com/getsentry/raven-js/blob/66a5db5333c22f36819c95844a1583489c1d2661/src/utils.js#L13

This is because when `Object.prototype.toString` is called with an instance of the error subclass, we get `"[object Object]"` instead of the expected `"[object Error]"`.

Example:

(This example mirrors the way `getstream` extends `Error`, but I have simplified it for clarity.)

``` js
{
  function MyError(message) {
    Error.call(this, message);

    this.name = 'MyError';
  }
  MyError.prototype = new Error();

  ({}).toString.call(new MyError('foo'))
  // "[object Object]"
}
```

If `MyError` correctly extended `Error`, `Object.prototype.toString` would report back `[object Error]`. For example, using ES2015 classes:

``` js
{
  class MyError extends Error {
    constructor() {
      super();

      this.name = 'MyError';
    }
  }

  ({}).toString.call(new MyError('foo'))
  // "[object Error]"
}
```

I have also tested this with the ES5 output of Babel and it also works as expected, suggesting it is possible to correctly extend `Error` in ES5 (without `class` support).

**Comment by dwightgunning** [comment]
Thanks much for pointing this out :) We use and love Sentry ourselves so I'd like to get this right.

I'll add to our backlog. If you're keen to submit a PR in the meantime, it would be welcome :)

**Comment by OliverJAsh** [comment]
@dwightgunning Thanks for the fast reply! Turns out I was wrong about this causing issues in Sentry. They fallback to an `instanceof Error` check, which this subclass returns `true` for, however this might be something worth fixing nonetheless.

**Comment by kenhoff** [comment]
Closing with https://github.com/GetStream/stream-js/pull/121.

**Comment by OliverJAsh** [comment]
The issue as described still remains, I was just wrong about it because the cause of my Sentry issue—so I would re-open this.

**Comment by dwightgunning** [comment]
Thanks for the heads up... I'll re-open for now while we take a look and consider next steps.

**Comment by ferhatelmas** [comment]
fixed for v5
