### ISSUE TITLE
Can't mark notification feed items as read

### ISSUE THREAD

**Issue by adylevy** [GetStream/stream-js#126]
code that used to work stopped working suddenly in the past week or so.
I am using the node api with this call to mark notification items as read but now it is not setting anything as read anymore.
 const client = stream.connect(....)
const feed = client.feed('notification','‌5a00ae86d7b1cb00150a0d03');
feed.get({mark_read: ['fe70fccc-d1ff-11e7-8080-800143da658c']});

response is valid and it returns the specific item as a first item (for this example) with is_read=false. i've seen another issue pointing out that it will get set on the next read but it's consistently returning false.

I tried changing feed.get to a string instead of an array, to the id of the group (?!) but nada.
The main thing here is that it used to work and stopped suddenly. would love to get some feedback on this subject.

(results[0] = {
  "activities": [
    {
      "actor": "5a199dd08d9bef001031cae5",
      "context": "user:5a199dd08d9bef001031cae5",
      "foreign_id": "friendship:request:5a199e128d9bef001031cb06",
      "id": "fe2012f0-d1ff-11e7-8080-800072d46a47",
      "object": "5a199e128d9bef001031cb06",
      "origin": null,
      "target": "friendship:5a199e128d9bef001031cb06",
      "time": "2017-11-25T16:45:06.847000",
      "to_actor": "5a00ae86d7b1cb00150a0d03",
      "verb": "friendship.request"
    }
  ],
  "activity_count": 1,
  "actor_count": 1,
  "created_at": "2017-11-25T16:45:07.377274",
  "group": "friendship:5a199e128d9bef001031cb06_friendship.request_2017-11-25",
  "id": "fe70fccc-d1ff-11e7-8080-800143da658c",
  "is_read": false,
  "is_seen": true,
  "updated_at": "2017-11-25T16:45:07.377274",
  "verb": "friendship.request"
}
regards

**Comment by jeffrysteven** [comment]
+1

**Comment by dwightgunning** [comment]
To clarify, the `mark_read` array should contain the Group Id ("fe70fccc-d1ff-11e7-8080-800143da658c" in your example). Are you able to confirm that's the value you tried?

Also if you'd like to email support@getstream.io with your App Id and details of the Feed Group and Feed Id we can look into it future.

**Comment by dwightgunning** [comment]
Closing this one out.
