### ISSUE TITLE
Typescript Definition: follow should have options arg as optional?

### ISSUE THREAD

**Issue by Francescu** [GetStream/stream-js#139]
👋
I'm new to Stream and wondering why `options` is optional in `unfollow` method and required for the `follow` method? 

Documentation doesn't show an use of the `options` argument.

Are the TS def/JSDoc wrong, or is  the doc not up to date?

**Comment by dwightgunning** [comment]
Indeed. Our TS type definitions are a work in progress. We'll make a fix for this asap. If you'd like to contribute a PR with additional type definitions it'd be most appreciated :)
