### ISSUE TITLE
How to generate a feed's token using server side signing?

### ISSUE THREAD

**Issue by harikrishnanq** [GetStream/stream-js#160]
In [stream-js](https://github.com/GetStream/stream-js) docs it is mentioned like 
```
// Generate a feed's token using server side signing
user1 = client.feed('user', '1', 'FEED_TOKEN');
```

But how can I do it? Could you provide me an example?

**Comment by dwightgunning** [comment]
Thanks for pointing out that this is unclear in the examples. Further along in the 'usage' sample you'll find the following snippet:

```
// creating a read-only feed token server side
readonlyToken = client.feed('user', '1').getReadOnlyToken();
// passed to client via template or api and initialized as such
user1 = client.feed('user', '1', readonlyToken);
```

If you're not using stream-js in a Node.js server-side environment, e.g. stream-python, there are are similar properties/functions on the equivalent Stream client class.  Our docs contain an example in the section on [Realtime updates](https://getstream.io/docs/#realtime).

I've made a tweak to the 'usage' example to improve readability. Thanks again.
