### ISSUE TITLE
Stream connect and missing token

### ISSUE THREAD

**Issue by trexanhvn** [GetStream/stream-js#161]
Hello,
I started to connect stream with apiKey, apiSecret and apiAppId in server side like this:
```
let client = serverStream.connect(streamConfig.apiKey, streamConfig.apiSecret, streamConfig.apiAppId)
let userFrancis = client.feed('users', 'francis')
```
But when I run it always return error
`Error: Missing token, in client side mode please provide a feed secret` at the line have `client.feed()`.

How can I make it right? B/c I reading docs and followed this.

Btw, have I used mongo to save my data? Or I just used in getstream.io?

**Comment by serranoarevalo** [comment]
How did you fix this?
