### ISSUE TITLE
Email redirect tracking isn't implemented

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/stream-js#175]
https://getstream.io/docs/#analytics_email

**Comment by dwightgunning** [comment]
Is this not implemented with `Client.createRedirectUrl` [here](https://github.com/GetStream/stream-js/blob/5dbe09baad44d58a8afe3aff744dec1eb023e251/src/lib/client.js#L569) (see also: [3.0.0 changelog](https://github.com/GetStream/stream-js/blob/57fc7fc8ff55debafeca741e14ee1f0837f7d95b/CHANGELOG#L178))?

Though I notice the function is only added to the `Client` class on node environments (`qs` is excluded on browser and react-native via package.json properties).

Is the requirement to expose this functionality in the browser and in react-native too?

**Comment by tbarbugli** [comment]
email redirect is implemented, closing
