### ISSUE TITLE
Update package.json requirements

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/stream-js#176]

**Comment by dwightgunning** [comment]
Our deps are pretty well up to date as of writing.

Github reports vulnerabilities in `hoek`, a downstream dependency of our devDependencies `karma` and the `karma-saurce-launcher`.

Karma contributors are discussing how they'll handle this: https://github.com/karma-runner/karma/issues/2994

karma-sauce-launcher has a [PR]( https://github.com/karma-runner/karma-sauce-launcher/pull/149) to update their dependency on `wd` which in turn will bump `hoek`.

**Comment by tbarbugli** [comment]
@dwightgunning we should update karma "^2.0.4" to make `npm audit` happy. Once that's done we can close this ticket
