### ISSUE TITLE
Failed to import getstream sdk on a server side: "ReferenceError: window is not defined"

### ISSUE THREAD

**Issue by stel** [GetStream/stream-js#187]
I'm trying to use `getstream-js` on the server side (typescript + webpack + serverless) and getting "ReferenceError: window is not defined" error at `.../lib/node_modules/getstream/dist/js/getstream.js:10:2`:
```js
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define([], factory);
	else if(typeof exports === 'object')
		exports["stream"] = factory();
	else
		root["stream"] = factory();
})(window, function() {          <--- HERE
```

I'm not sure, but it might be related to the UMD modules issue in Webpack 4 (https://stackoverflow.com/questions/49111086/webpack-4-universal-library-target).

**Comment by stel** [comment]
3.17.0 works fine though.

**Comment by tbarbugli** [comment]
Closing this, let us know if you can reproduce this on 3.17 or newer

**Comment by stel** [comment]
Oh, sorry, I wasn't clear enought: it works fine on 3.17 but doesn't on 3.19.
