### ISSUE TITLE
How to get the number of feeds and activities in a flat feed?

### ISSUE THREAD

**Issue by InVincible2016** [GetStream/stream-js#188]
let's say I have a flat feed group named 'user', and 10 users wit distinct user ids (user:userid), each user has 50 activities.

How do I get the number of users in a feed group, i.e. 10 in this case, as well as the number of activities in each user's feed, i.e. 50 in this case?

**Comment by tbarbugli** [comment]
@InVincible2016 this is not exposed by the APIs at the moment
