### ISSUE TITLE
Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by atieq-rehman-confiz** [GetStream/stream-js#191]
i am trying to fetch activities based on user timeline using getstream-js.

the first call works fine and returns required no of activities along with 'next' url

when i try to do a call with 'next' url it throws error `Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response.`

i tried same header settings as it was in first request but not working. below is my ajax call. 

<pre><code>jq.ajax({
                    url: next,
                    type: "GET",
                    //dataType: 'jsonp',
                    beforeSend: function (request) {
                        request.setRequestHeader("Authorization", "<?php echo $user_timeline?>" + "<?php echo $logged_in_user?>" + ' ' + "<?php echo $token?>");
                        request.setRequestHeader("Stream-Auth-Type", "simple");
                        request.setRequestHeader("access-control-allow-headers", "x-requested-with, content-type, accept, origin, authorization, x-csrftoken, x-stream-client, stream-auth-type");
                        request.setRequestHeader("access-control-allow-methods", "GET, POST, PUT, PATCH, DELETE, OPTIONS");
                        request.setRequestHeader("access-control-allow-origin", "x-requested-with, content-type, accept, origin, authorization");
                        request.setRequestHeader("content-type", "application/json;charset=utf-8");

                        jq(window).data('ajaxready', false);
                    },
                    success: function (data) {
                        console.log('old');
                        next = "https://api.stream-io-api.com" + data.next;
                        addActivities(data.results);
                    }
                    ,
                    complete: function (request) {
                        jq(window).data('ajaxready', true);
                    },
                    error: function (jqXHR, exception) {
                        console.log(jqXHR);
                        console.log(exception);
                    }
                });</pre></code>

i m using jquery-2.1.1 with php

**Comment by tbarbugli** [comment]
You should use `feed.get` with limit + offset or id_lt + limit parameters to do pagination (you can also parse the params and values from the next field but that's usually not necessary)

**Comment by atieq-rehman-confiz** [comment]
feed.get worked but i have to parse 'next' url to get activity id
