### ISSUE TITLE
Allow to set browser option manually

### ISSUE THREAD

**Issue by 7flash** [GetStream/stream-js#195]
In some cases backend can have global window variable. In my case, I have this issue when I am running tests with neutrino.

https://github.com/GetStream/stream-js/blob/4025a6bb612451fc669c4656c6e9e41ff173a80f/src/lib/client.js#L75

**Comment by JelteF** [comment]
Thank you for your PR and bugreport. I fixed this in a slightly different way here: https://github.com/GetStream/stream-js/commit/5604c7ad865c11a63e5d8954008f29a1237dcd30

With my fix you can also set browser to true if needed. 

I will close this now, since it's fixed.
