### ISSUE TITLE
server not conforming to faye SPEC

### ISSUE THREAD

**Issue by thesyncim** [GetStream/stream-js#198]
Dear all,

first of all i am not sure if this is the right place for this bug report.

i'm currently  implementing a go client for faye protocol and it looks like you are not conforming with the faye spec.
 
let me expand it:

According to the official documentation, when we send a /meta/publish request, the response [**MUST** include the subscription](https://github.com/faye/faye/blob/master/src/protocol/client.js#L202)

i need this field to be populated in order to "redirect" the error for the subscriber.
one workaround can be, using the field id !

this is currently happening using websocket protocol

here is the entire req/resp workflow

client send handshake:
```json
[
 {
  "channel": "/meta/handshake",
  "version": "1.0",
  "supportedConnectionTypes": [
   "websocket"
  ],
  "advice": {}
 }
]
```

server replies
```json
[
 {
  "channel": "/meta/handshake",
  "version": "1.0",
  "supportedConnectionTypes": [
   "websocket",
   "long-polling",
   "cross-origin-long-polling",
   "callback-polling"
  ],
  "successful": true,
  "clientId": "1-bc79c055-07c4-4e1e-86c3-3422af5cd64e",
  "advice": {
   "reconnect": "retry",
   "timeout": 30000
  }
 }
]
```
client send connect
```json[
 {
  "channel": "/meta/connect",
  "connectionType": "websocket",
  "id": "1",
  "clientId": "1-bc79c055-07c4-4e1e-86c3-3422af5cd64e",
  "advice": {}
 }
]
```

client send request subscribe
```json
 [
 {
  "channel": "/meta/subscribe",
  "ext": {
   "user_id": "site-41005-feed-go1",
   "api_key": "j2ryhp8g5f4f",
   "signature": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3Rpb24iOiJyZWFkIiwiZmVlZF9pZCI6ImdvMSIsInJlc291cmNlIjoiZmVlZCJ9.DLKhYIeJbjrN-HDb2DL4XNKu4SqJAWEU28vx1NuOZiY"
  },
  "id": "2",
  "clientId": "1-bc79c055-07c4-4e1e-86c3-3422af5cd64e",
  "advice": {},
  "subscription": "/site-41005-feed-go1"
 }
]
```

server replies 
```json
{
 "channel": "/meta/subscribe",
 "id": "2",
 "advice": {},
 "error": "API Key j2ryhp8g5f4f is not valid for app id 41005."
}
```
as we can see the last response doesn't include the subscription.

thank you for your time,
Marcelo Pires

**Comment by tschellenbach** [comment]
Stream's realtime backend is a port of Faye written in Go. Thanks for spotting this issue, should be an easy fix

**Comment by thesyncim** [comment]
other possible bug,

the current implementation is not responding to /meta/connect and[ according to the spec](https://github.com/faye/faye/blob/master/src/protocol/client.js#L133) it should.

that,s not a big deal because we will get the error of the first Read.

**Comment by tbarbugli** [comment]
I guess

**Comment by thesyncim** [comment]
another possible bug
[/meta/connect is returning data ](https://github.com/faye/faye/blob/master/src/protocol/client.js#L142)
```=== RUN   TestSubscribe
websocket.go:129: sending request [
 {
  "channel": "/meta/handshake",
  "version": "1.0",
  "supportedConnectionTypes": [
   "websocket"
  ],
  "advice": {}
 }
]
websocket.go:157: handshake response [
 {
  "channel": "/meta/handshake",
  "version": "1.0",
  "supportedConnectionTypes": [
   "websocket",
   "long-polling",
   "cross-origin-long-polling",
   "callback-polling"
  ],
  "successful": true,
  "clientId": "1-ad3a37b0-3f0c-42c7-a542-79fb68c71408",
  "advice": {
   "reconnect": "retry",
   "timeout": 30000
  }
 }
]
websocket.go:129: sending request [
 {
  "channel": "/meta/connect",
  "connectionType": "websocket",
  "id": "1",
  "clientId": "1-ad3a37b0-3f0c-42c7-a542-79fb68c71408",
  "advice": {}
 }
]
websocket.go:129: sending request [
 {
  "channel": "/meta/subscribe",
  "ext": {
   "user_id": "site-41007-feed-go1",
   "api_key": "j2ryhp8g5f4f",
   "signature": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3Rpb24iOiJyZWFkIiwiZmVlZF9pZCI6ImdvMSIsInJlc291cmNlIjoiZmVlZCJ9.DLKhYIeJbjrN-HDb2DL4XNKu4SqJAWEU28vx1NuOZiY"
  },
  "id": "2",
  "clientId": "1-ad3a37b0-3f0c-42c7-a542-79fb68c71408",
  "advice": {},
  "subscription": "/site-41007-feed-go1"
 }
]
feed.go:144: {
 "channel": "/site-41007-feed-go1",
 "id": "2",
 "clientId": "1-ad3a37b0-3f0c-42c7-a542-79fb68c71408",
 "advice": {},
 "data": {
  "deleted": [],
  "feed": "go:1",
  "new": [
   {
    "actor": "go:1",
    "foreign_id": "",
    "group": "tweet_2018-09-05",
    "id": "8a20ce1d-b123-11e8-acdf-0a56d1adc092",
    "object": "1",
    "origin": null,
    "target": "",
    "time": "2018-09-05T15:51:23.417757",
    "tweet": "Hello world",
    "verb": "tweet"
   }
  ]
 },
 "subscription": "/site-41007-feed-go1"
}
feed_test.go:253: {8a20ce1d-b123-11e8-acdf-0a56d1adc092 go:1 tweet 1   2018-09-05 15:51:23.417757 +0000 UTC  [] 0 map[group:tweet_2018-09-05 tweet:Hello world]}
feed.go:144: {
 "channel": "/meta/connect",
 "successful": true,
 "id": "1",
 "clientId": "1-ad3a37b0-3f0c-42c7-a542-79fb68c71408",
 "advice": {
  "reconnect": "retry",
  "timeout": 30000
 },
 "data": {
  "deleted": [],
  "feed": "go:1",
  "new": [
   {
    "actor": "go:1",
    "foreign_id": "",
    "group": "tweet_2018-09-05",
    "id": "8a20ce1d-b123-11e8-acdf-0a56d1adc092",
    "object": "1",
    "origin": null,
    "target": "",
    "time": "2018-09-05T15:51:23.417757",
    "tweet": "Hello world",
    "verb": "tweet"
   }
  ]
 },
 "subscription": "/site-41007-feed-go1"
}

```

**Comment by tbarbugli** [comment]
@thesyncim I was mislead by the fact that you posted a failed `meta/connect` request response. The subscription is also not returned when `meta/connect` is successful.

**Comment by tbarbugli** [comment]
I just tried the JS Faye client on the browser and I can see a message to "/meta/connect" channel with a response from the server.

This is what the client sends:

**message** ```[{"channel":"/meta/connect","clientId":"1-ebf4c20f-1171-409b-8cf4-9aa2ead38eb6","connectionType":"callback-polling","id":"2","advice":{"timeout":0}}]```

**jsonp** ```__jsonp2__```

This is the response I get from the server:

```
/**/__jsonp2__([{"channel":"/meta/connect","clientId":"1-ebf4c20f-1171-409b-8cf4-9aa2ead38eb6","id":"2","successful":true,"advice":{"reconnect":"retry","interval":0,"timeout":30000},"duration":"0.30ms"}])
```

**Comment by thesyncim** [comment]
i forgot to mention that i'm using websocket transport. 
due to the nature of callback-polling (req/resp) the server must always respond.
what happen if you use websocket transport?

**Comment by thesyncim** [comment]
this is prtscr from your website.
we can see 4 requests 1 `/meta/connnect` and 3 `/meta/subscribe` and only 3 replies from the server. because the connect was successfully the websocket transport didnt responde to the `/meta/connect` 
![websocket example](https://user-images.githubusercontent.com/916501/45223226-f8a2a200-b2b6-11e8-8f51-ebddf51e754c.PNG)

**Comment by thesyncim** [comment]
also i can see that you already fixed the issue. thanks

**Comment by tbarbugli** [comment]
looks like you were faster than me to test that :) Btw we did not make any changes to the Faye server (the spec bug you reported is now in our backlog but it is not fixed yet).

**Comment by thesyncim** [comment]
i see, so that means the you are not setting the subscription only when `/meta/subscribe` fails
