### ISSUE TITLE
Couldn't get real-time updates working in node

### ISSUE THREAD

**Issue by tetsuo** [GetStream/stream-js#199]
I'm trying to receive real-time updates through WebSocket. (node.js v10.4.1)

Do you see any mistakes in here? Callback to `userFeed.subscribe` is never fired.

```
 const gsc = gs.connect('x', 'y', '1')

  const userFeed = gsc.feed('user', 'bob')

  const sub = userFeed.subscribe(data => {
    console.log('RECV', data)
  })
  .then(data => {
    console.log('SUBSCRIBED')
  })
  .catch(reason => {
    debugger
  })

  userFeed.addActivity({
    actor: 'user:bob',
    status: 'Hello' + Math.random(),
    verb: 'status',
    object: '1'
  })
  .then(data => {
    console.log('SEND', data)
  })
  .catch(reason => {
    debugger
  })
```

**Comment by tbarbugli** [comment]
I suggest moving `userFeed.addActivity` code inside the 'subscribed' callback; this will remove the add/subscribe race.

**Comment by tbarbugli** [comment]
Also good to double check that the user feed group for this app has realtime enabled (you can check that on Stream's dashboard)

**Comment by tetsuo** [comment]
Ah, thanks a lot. Not sure what I was thinking :) adding the activity after subscription resolves works like a charm 👍
