### ISSUE TITLE
Code needs to update naming conventions

### ISSUE THREAD

**Issue by catilac** [GetStream/stream-js#204]
First of all, thank you for this service. It's been great so far. As a new customer there are some things that I find confusing, especially when everything is marketed to people trying to build social networks. 

https://github.com/GetStream/stream-js/blob/master/src/lib/feed.js#L144
`targetUserId` implies we can only follow users. But this system is more robust than that, and makes things more confusing.

**Comment by ferhatelmas** [comment]
@mahboubii since we're going for breaking changes, we might try to handle this too. It's very inconvenient and error prone. 

At least, in the simpler version having a consistent case style (snake vs camel) would be better.
