### ISSUE TITLE
client.feed don't automatic get actor reference

### ISSUE THREAD

**Issue by phongloihong** [GetStream/stream-js#205]
Dear all,

When i use 
`var user1 = client.feed('user', '1', '{{ user_feed_1.token }}');`
`user1.subscribe(() => console.log(data));`
i get `actor:"SU:5bd14ca4d518646ff69b39fd"`
how i can get my actor detail data ?

thank you for your time.

**Comment by tbarbugli** [comment]
```
userSession.getUser('amazing-user')

**Comment by phongloihong** [comment]
Thank you for all your help.

**Comment by galenp** [comment]
Hello,

Can we track the progress of realtime auto-enrich from collections anywhere? It's a feature we're itching to use.
