### ISSUE TITLE
Can't get real time updates in client to work

### ISSUE THREAD

**Issue by florist-gump** [GetStream/stream-js#206]
I'm having some problems getting real time updates to work in the client.

```
const client = stream.connect(APIKey, null, AppID);
const feed = client.feed("user", userName, token);
feed.subscribe((data) => {
    console.log("subscribed", data);
}).then(() => {
    console.log("promise resolved");
}, (e) => {
    console.log("error", e);
});
```

The error I'm getting is: "Invalid subscription format fields."

I've enabled real time notifications in the Feed Group Config and getting the feed via `feed.get(...)` also works without any problems.

Any idea what the issue could be?

**Comment by tschellenbach** [comment]
@thesyncim

**Comment by florist-gump** [comment]
@tbarbugli The value of userName was '1' together with the corresponding token

**Comment by florist-gump** [comment]
The issue was that I used the App Name instead of the App ID when first doing the stream.connect. After updating the AppID it worked without any issues.

**Comment by AdamGold** [comment]
I have the same problem. Using the correct app ID and token.
