### ISSUE TITLE
Lack of API docs

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/stream-js#21]
emberjs uses this:
http://yui.github.io/yuidoc/

**Comment by matthisk** [comment]
Investigated a bit, jsdoc seems the most convenient to work with. This is what the code looks like with the doc comments: https://github.com/GetStream/stream-js/blob/documentation/src/lib/client.js. You can generate the docs if you check out that branch and run `npm install -g jsdoc` and `jsdoc src/**/*.js`

**Comment by tschellenbach** [comment]
Nice, looks pretty good. We'll pick up the improvements to the stream-js client in the next mailing. Great work.

**Comment by matthisk** [comment]
Committed end result on documentation branch: [final generated result](http://htmlpreview.github.io/?https://github.com/GetStream/stream-js/blob/documentation/docs/getstream/2.2.2/index.html). It would be cool if we could use something like [wicked](https://github.com/thlorenz/wicked) to use the github wiki as a documentation page, but this tool looks like it is not receiving support, and has an old jsdoc dep (resulting in errors and incorrect behavior).

**Comment by matthisk** [comment]
#59
