### ISSUE TITLE
Invalid docs and wrong activity timestamp

### ISSUE THREAD

**Issue by mikestaub** [GetStream/stream-js#212]
The client.getActivities() method described here:

https://getstream.io/docs/js/#retrieve-activities-by-id

Specifies the 'foreignIDTimes' arg as using 'foreign_id' but the correct usage is 'foreignID'. This tripped me up for a minute.

Also, even when I use the timestamp that I created the activity with, I still cannot retrieve the activity. I confirmed this was because of the precision of the timestamp.

```
{  
   "detail":"invalid timestamp \"2018-11-22T19:25:31.811Z\"",
   "status_code":400,
   "code":15,
   "exception":"BadInputException",
   "duration":"0.15ms"
}
```

When viewing that activity from the explorer UI, the time is `2018-11-22T19:25:31.811000
`. In javascript, when I do `new Date('2018-11-22T19:25:31.811000').toISOString()` however, I get '2018-11-22T19:25:31.811Z' which does not work.

I would use the activity's ID, but that was not returned to me when I added it with the `client.addToMany()` method.

What do you suggest I do to retrieve the activity? ( besides hacking the time string )

**Comment by tbarbugli** [comment]
this is indeed not a great user experience, we are moving our docs examples to a test suite so that similar issues are not going to happen again in the future.

Regarding the time handling, we will put a fix to this asap

**Comment by tbarbugli** [comment]
@mikestaub we added better support for time parsing server-side and deployed a patch earlier today. Please re-open if you still have issues with this
