### ISSUE TITLE
Unable to follow feed 

### ISSUE THREAD

**Issue by Djiit** [GetStream/stream-js#221]
I'm trying to follow a user 'user' feed from another user's 'timeline' feed. Copy/pasting from the doc, I got this code (sensitive data changed):

    var stream = require('getstream');
    // Instantiate a new client (server side)
    client = stream.connect('api_key', 'api_secret', 'app_id');

    var chris = client.feed('user', 'chris');
    
    // Add an Activity; message is a custom field - tip: you can add unlimited custom fields!
    chris.addActivity({
      actor: 'chris',
      verb: 'add',
      object: 'picture:10',
      foreign_id: 'picture:10',
      message: 'Beautiful bird!'
    }).then(
      null, // nothing further to do
      function(err) {
    console.log(err)
        // Handle or raise the Error.
      }
    );
    
    // Create a following relationship between Jack's "timeline" feed and Chris' "user" feed:
    var jack = client.feed('timeline', 'jack');
    jack.follow('user', 'chris').then(
      null, // nothing further to do
      function(err) {
    console.log(err)
        // Handle or raise the Error.
      }
    );

I also tried the client-side version (generating server-side read/write token; but the result is the same.

Here is the error I have

    message: '{"detail":"You do not have permission to perform this action.","status_code":403,"code":17,"exception":"NotAllowedException"

Did I miss something  here ?

**Comment by ronipozn** [comment]
I got the same error after upgrading to 4.0.3. Please help.

**Comment by Djiit** [comment]
I use this snippet : 
```
const feed = client.feed('user', '<user_id>')
const userToken = feed.token

(... here I save the token in DB and so on)
```

**Comment by tbarbugli** [comment]
@Djiit thx for sharing that. I just pushed a new version of the client to NPM (v4.0.4). Can you test with that version?

**Comment by Djiit** [comment]
Sure, let me check.

PS : reading your post again, I realized i didnt user getReadWriteToken during my client-side tests. Should I use `feed.getReadWriteToken()` or `feed.token`?

**Comment by tbarbugli** [comment]
@Djiit Both work. FYI `feed.getReadWriteToken()` is there just for backwards-compatibility 

From v4 on the way to go is to use `client.createUserToken` server-side and then use the generated token client-side.

```js
const userToken = client.createUserToken('the-user-id');
```

```js
var stream = require('getstream');

// Instantiate new client with a user token
client = stream.connect('apikey', userToken,  'appid');
```

I just realized the example code on this repo's README still suggest the previous approach, going to change that asap 💨

**Comment by Djiit** [comment]
@tbarbugli your example works like a charm and I'm able to follow a feed form the client side with the token from `createUserToken` and instanciating the client the right way.

You might want to check the code as I didnt remember seeing this client instanciation usage (the docs tells you to pass `null` as the token).

I'm leaving this open if you want to track the server-side bug. I'm happy to help, tell me if I can test anything.

**Comment by tbarbugli** [comment]
@Djiit thanks for being super helpful on this; my previous patch did only fix one case. 4.0.5 should be the final fix to this. Could you point me to the docs with `null` code snippet? We are replacing all with the new approach but it looks like we missed that one.

**Comment by Djiit** [comment]
Thanks, it works great on 4.0.5 !

**Comment by ronipozn** [comment]
Thank you for the quick fix, works great now!
