### ISSUE TITLE
Undefined STREAM_URL

### ISSUE THREAD

**Issue by danielneri** [GetStream/stream-js#223]
I'm running into an odd issue whereby `process` is defined but `process.env` is undefined. I'm running an Angular application that has node typings to get around another angular bug, which looks to be tripping up the Stream lib.

The Stream source has this line which could be modified to safely check both objects:

`(typeof process !== 'undefined' && process.env.STREAM_URL)`

**Comment by gavinhuangflynn** [comment]
I have the same issue on an Angular application,

**Comment by ferhatelmas** [comment]
@danielneri @gavinhuangflynn Do you still have the issue ?

**Comment by ferhatelmas** [comment]
#337
