### ISSUE TITLE
Package size exceeded the configured limit of 50 MB

### ISSUE THREAD

**Issue by akute** [GetStream/stream-js#224]
Hi!

Noticed that the script distributed via jsdelivr

`https://cdn.jsdelivr.net/npm/getstream/dist/js_min/getstream.js`

is responding with 403 response:

`Package size exceeded the configured limit of 50 MB.`

Could you please fix the settings on JSDelivr to solve the issue?

**Comment by MartinKolarik** [comment]
There's a 67 MB `sample.txt` which contains some binary data. Sure doesn't look like something that should be in the npm package.

**Comment by tbarbugli** [comment]
@akute @MartinKolarik thank you for reporting this; the previous release unfortunately included a binary file used for some tests. I pushed a new patch version, jsdelivr is serving the files again.
