### ISSUE TITLE
Signature is invalid

### ISSUE THREAD

**Issue by tylermassey** [GetStream/stream-js#225]
Whenever I call `feed.get` in my frontend client, I get a 403 `signature is invalid` error.

The odd thing about this is that after I `get` the feed, I also `subscribe` to the feed, and that is working.

Here is my frontend code

```ts
const client = stream.connect(
  appKey,
  userToken,
  appId,
  "us-east"
);

const feed = client.feed("user", userId);

feed
  .get({ limit: 5 })
  .then((results: any) => {
    handleData(results);
  })
  .catch((err: any) => console.log(err));

feed.subscribe((data: any) => {
  handleNewData(data);
});
```

Here is how I generate the token on my backend

```ts
const client = stream.connect(
  appKey,
  appSecret,
  appId,
  "us-east"
);
const userToken = client.createUserToken(userId);
return userToken;
```

I'm following what is in the docs as far I can tell, and again, subscribing to new activities **is** working.

**Comment by tylermassey** [comment]
@tbarbugli Yep, the `userId` values are the same.

I'm using the most recent version on my client and server: 4.0.6.

**Comment by tbarbugli** [comment]
@tylermassey also same `apiKey` and `appId`?

**Comment by tylermassey** [comment]
@tbarbugli 😅 this is embarrassing but they weren't the same. After making that change, it's working now. Thank you for the help!

**Comment by tbarbugli** [comment]
no worries, glad we figured it out :)

**Comment by MatiurRehman900** [comment]
I am generating a userToken using STREAM_APP_KEY and STREAM_API_SECRET, and I am also generating a JWT token. However, when I use that token in react-activity-feed, I am getting an 'signature is invalid' error in the network. Can anybody help me with that? This is my code where I am generating the token.

import { StreamChat } from 'stream-chat';
import { useSession } from "next-auth/react";

export default async (req, res) => {
    try {
        const { userId } = req.query;
        const client = StreamChat.getInstance(
            process.env.STREAM_APP_KEY,
            process.env.STREAM_API_SECRET
        );

        const userToken = await client.createToken(userId);

        res.status(200).json({ userToken });
    } catch (error) {
        res.status(500).json({ error: 'Something went wrong Please try again after some time.' });
    }
};
