### ISSUE TITLE
Marking notifications as seen without re-fetching data.

### ISSUE THREAD

**Issue by dolsem** [GetStream/stream-js#230]
In our React Native application we have a notifications screen that pre-fetches notifications as soon as the app is opened and the unseen counter is displayed in the navigation bar. We want to clear the counter only when the user opens the screen with notifications. I was only able to find a way to mark notifications as seen as part of the `get()` method. Is it possible to do so without re-fetching data?

**Comment by tbarbugli** [comment]
Get is the only way to mark seen/read. @JelteF is get(limit=0)  with mark seen/read a valid workaround?

**Comment by JelteF** [comment]
Yes, get(limit=0) is the best way to only get the counters.
