### ISSUE TITLE
feed.get() broken with filters

### ISSUE THREAD

**Issue by mikestaub** [GetStream/stream-js#235]
Here is a snippet from my code:

```
	          const userFeed = this.client.feed(this.feedGroups.TIMELINE, userId);
	          const activity = await userFeed.addActivity(act);
	          const response1 = await userFeed.get({
	            limit: 1,
	          });
	          const response2 = await userFeed.get({
	            id_lte: activity.id,
	            id_gte: activity.id,
	            limit: 1,
	          });
	          console.log(
	            response1.results[0].activities[0],
	            response2.results,
	          );
```

Response1 has the new activity, response2 does not. This appears to be a bug.

**Comment by mircea-cosbuc** [comment]
Hi @mikestaub . Am I correct in assuming `this.feedGroups.TIMELINE` is an aggregated or notification feed? If it is indeed the case, then pagination won't work as expected when using the activity id, but the group id provided in your first response. e.g.
```js
const response2 = await userFeed.get({
  id_lte: response1.results[0].id,
  id_gte: response1.results[0].id,
  limit: 1,
});
```
There is a special mention about it in the [docs on retrieving activities](https://getstream.io/docs/#retrieve).

**Comment by ferhatelmas** [comment]
> When using id_lte to paginate an aggregated feed, use the ID of the group that is returned from the API. Using an ID of an individual activity within the group will not work and result in an error.

This case is documented in docs and no more user input is given so closing.
