### ISSUE TITLE
Typescript: createUserToken(id) missing

### ISSUE THREAD

**Issue by wsdt** [GetStream/stream-js#236]
Typescript definition of StreamClient is `createUserToken(userId)` missing. 

Please add as I spent half an hour wondering why that function does not exist. 
Thank you :)

**Comment by lafferty151** [comment]
Any update on this issue?

**Comment by obibring** [comment]
I just ran into this and shocked to see it's been open since January.

**Comment by wsdt** [comment]
For all who run into this issue: You may add it to the getstream declaration file in the meantime as long as it is not resolved natively.
