### ISSUE TITLE
Get a user session read-write token

### ISSUE THREAD

**Issue by anik-jagtap** [GetStream/stream-js#237]
Hi,
I was looking for a user token that can handle read and write of feeds for a particular user irrespective of the feed group. Using `JWTUserSessionToken` of `getstream/lib/lib/signing` i am able to generate a read only token. Can i get a read and write token using this? And is there any public method for this ?

**Comment by mahboubii** [comment]
Generally, you should be using the `client.createUserToken()` function to generate user tokens, this token allows users to access feeds with feed id the same as user id.
If you need something more specific, you can leverage the util function in `signing.JWTScopeToken()` to generate more specific access tokens. Please refer to the docs for more information regarding this https://getstream.io/docs_rest/#authentication

Feel free to re-open this issue if you still had any problems.
