### ISSUE TITLE
How i can add reaction serverside.

### ISSUE THREAD

**Issue by phongloihong** [GetStream/stream-js#242]
Hi! 
I used version 3 before but after upgrading version 4 I can't find the way to create a new reaction in serverside. Because I need to do some logic before add new reaction.
Documents only show create new in client side 
`
const client = stream.connect(STREAM_API_KEY, userToken,  APP_ID);
`
`
let like = await client.reactions.add("like", activityId);
`
Thanks for the help.

**Comment by frenchdonuts** [comment]
Hey @phongloihong did you find a way around this? I'm trying to do the same thing.

**Comment by phongloihong** [comment]
Hi @frenchdonuts 
I'm moved reaction action to the client-side and use webhook to update in my local database
