### ISSUE TITLE
Unable to use updateActivityToTargets

### ISSUE THREAD

**Issue by hypervillain** [GetStream/stream-js#243]
Hello Stream,

starting from a simple feed, I'm trying to assign some tasks to users by mentioning them in an existing activity. Unfortunately, I keep receiving this error message: `activity is not found for the couple foreign_id=x, time=y`.

This is how I call the method 👇
```javascript
async function debug(user, id) {
  return new Promise((resolve, reject) => {
    const feed = client.feed(FEED, id)
    feed.addActivity({
      actor: client.user(user).ref(),
      verb: 'request',
      object: `document-id:${Math.random()}`,
      foreign_id: `foreign-id-${Math.random()}`,
    }).then(({ foreign_id, time }) => {
       feed.updateActivityToTargets(foreign_id, time, [user])
       .then(resolve)
       .catch(reject)
   })
 })
}
```
I am under the impression that I'm not sending the right data types. I tried replacing `time` with `new Date(time)` and `new Date(time).toISOString()` but it did not work either.

Do you guys have any idea on what I could be doing wrong?
Any help appreciated 🙌

**Comment by tbarbugli** [comment]
in order to update activities you need to create them with `time` and `foreign_id`

```js
async function debug(user, id) {
 const t = new Date();
 return new Promise((resolve, reject) => {
    const feed = client.feed(FEED, id)
    feed.addActivity({
      actor: client.user(user).ref(),
      verb: 'request',
      object: `document-id:${Math.random()}`,
      foreign_id: `foreign-id-${Math.random()}`,
      time: t
    }).then(({ foreign_id, time }) => {
       feed.updateActivityToTargets(foreign_id, time, [user])
       .then(resolve)
       .catch(reject)
   })
 })
}
```

**Comment by hypervillain** [comment]
Hey @tbarbugli, thank you for your answer!

I actually had a `time` argument in my code but was trying to update activities that were created earlier.. Silly mistakes :) Do you know why you need to pass a time parameter when it's set by default on Stream side?
