### ISSUE TITLE
Misleading `user_id` usage for feed tokens

### ISSUE THREAD

**Issue by olivermack** [GetStream/stream-js#246]
Hi,

I'm having a couple of additional (flat) feeds in my setup and there seems to be some issue - either in my brain or in the codebase:
I already got my head around the fact that in most cases the ID-part of the feed slug is mostly called `user_id` but when I try to get a read-only token for a particular feed the client always complains about `user_id is missing in user token`.

An example of my setup may make it bit more clear: 
Imagine there are two (flat) feeds, "user" and "product". A user of my system shall be able to see the activities on any product. Let there be a user with ID `userid1` and a product with id `prodid1`. Thus, there may be two feeds, `user:userid1` and `product:prodid1`.
When I obtain a session token for the user `user1` I can retrieve the feed `user:userid1` without any issues. When I try to fetch the product feed I get an 403 saying `you don't have permission to do this`. Now, when you want to get a read-only token for the product-feed (in my case in php via `$client->getFeed('product', 'prodid1)->getReadOnlyToken()`) I do get a token but this token does not contain a `user_id`. The only token I was able to generate which does in fact contain a `user_id` is the "User Session Token". I was able to generate a valid token by fooling around, like initializing it the product id: `$this->client->createUserSessionToken('prodid1')`... anyway, this seems not to be the right way to me as the "just getting a token"-approach is semantically not what I'm aiming for. In fact, I want to get a token, created from my backend using apiKey+secret for the particular feed `product:prodid1` requested by the user `user1`.

I'm posting the issue in the `stream-js` repo because I'm getting the error in the `lib/client.js` (although I know that multiple components play a role here)

Sorry if I got something completely wrong concept-wise. I appreciate any hint! :) 

Best

**Comment by tbarbugli** [comment]
Auth tokens are either resource-based or user based. Resource based tokens allow you to grant permissions for the resource name, action type and user_id (eg. "feed", "read", "*" is what you get from a read-only token).

User ID based auth instead allows you to perform API calls as a specific user; as a user your are allowed to read/write your own feeds and follow other user feeds. With this system you can also allow specific actions to be public (eg. make a feed group readable by all users). If that solves your needs you can send an email to support and we'll configure it for your app (atm this is not exposed on the Dashboard).

Both permission systems don't allow you to work with groups (eg. user X can write to feed Y, ...) if that's your use-case we suggest moving the API calls server-side where such business logic already exist.
