### ISSUE TITLE
'You are publicly sharing your App Secret' when using StreamApp react component

### ISSUE THREAD

**Issue by varun85jobs** [GetStream/stream-js#249]
I am using the getStream.io React component as follows:
```
<StreamApp
    apiKey='apiKey'
    appId='appId'
    token='token'
>
  <FlatFeed />
</StreamApp>
```
When I am hard-coding the above values, I do not see any issue and the app works correctly.

However, when I try to pass the token as state variable ( Token is generated on the server side and returned to user on client side on signup/login), I get an exception as follows :

![image](https://user-images.githubusercontent.com/16530002/58735434-4e454e80-83f2-11e9-801f-c0eb71380840.png)

Has anyone else seen this issue before? If yes, how did you get around this issue. Any help is highly appreciated.

**Comment by PDiasG** [comment]
Hey, I am having the same issue. How did you figure it out? Thanks!

**Comment by varun85jobs** [comment]
Hi,
I was getting the token value from the server and passing it to the StreamApp component.
Between the time it took to fetch the token from server, `empty` value was getting passed to `token `prop of the `StreamApp `component.As the `empty` token value isn't valid, it was throwing this exception.The way I fixed this was passing token to StreamApp only when it is non-empty. Something like below in react code:

`{notificationToken !== '' && <React.Fragment> <StreamApp apiKey="api_key" appId="appid" token={notificationToken} > <NotificationDropdown notify Group={Notification} right={true}/> </StreamApp>}`

Hope that helps to solve your issue.
