### ISSUE TITLE
Upload image from backend

### ISSUE THREAD

**Issue by phongloihong** [GetStream/stream-js#250]
When I'm trying to upload an image by 
`clent.images.upload(dataBuffer)`

I get an error with status 400
`message: '{"detail":"`file` form field missing or not a file","status_code":400,"code":4,"exception":"InputException","duration":"0.28ms"} with HTTP status code 400' }`

I'm trying everything but can't find out how to fix this problem.

**Comment by phongloihong** [comment]
I trying to convert image URL to image URI it still no work and I get a new error:
`TypeError: source.on is not a function`

**Comment by mahboubii** [comment]
@phongloihong for uploads in Node you need to pass in a [DataStream](https://nodejs.org/api/stream.html) and a file name.
```js 
file = fs.createReadStream('./hello.jpg');
client.images.upload(file, "hello.jpg");
```
feel free to re-open this issue if you still need more help with this.

**Comment by SeanDunford** [comment]
@mahboubii - Sorry to bump an old thread but there seems to be a mismatch in expected typings when using TypeScript. 


The following code: 
```
    const fileStream = await fs.createReadStream(absolutePathToImage);
    const result = await streamClient.images.upload(fileStream);
```
Produces this error: 
```
TSError: ⨯ Unable to compile TypeScript:
scripts/stream/uploadImageToStream.ts(11,53): error TS2345: Argument of type 'ReadStream' is not assignable to parameter of type 'string | File | Buffer | ReadStream'.
  Type 'ReadStream' is missing the following properties from type 'ReadStream': isRaw, setRawMode, isTTY, write, and 24 more.
```

But forcing a type conversion like so: 
```
    const fileStream = await fs.createReadStream(absolutePathToImage);
    const result = await streamClient.images.upload(
      (fileStream as unknown) as NodeJS.ReadStream
    );
```   

Will allow the upload to work. 


I believe the types for the upload function 
```
  upload(
    uri: string | File | Buffer | NodeJS.ReadStream,
    name?: string,
    contentType?: string,
    onUploadProgress?: OnUploadProgress,
  ) {
    return this.client.upload('images/', uri, name, contentType, onUploadProgress);
  }
```

need to be extended to include `fs.ReadStream`

**Comment by ferhatelmas** [comment]
we have `@types/node` as a peer dependency, if you have it in your project, it should do the trick for correct typing

**Comment by SeanDunford** [comment]
@ferhatelmas 

I still get the same error message with `@types/node` in either deps, devDeps, or PeerDeps. 

Even created a new project to test outside of my current config. 

`package.json`

```
{
  "dependencies": {
    "getstream": "^8.0.1",
    "typescript": "^4.7.4",
    "@types/node": "^18.0.4"
  },
  "peerDependencies": {
    "@types/node": "^18.0.4"
  }
}
```

`index.ts`
```
import Path from 'path';
import fs from 'fs';
import stream from 'getstream';

const apiKey= ''
const apiSecret = '';
const apiAppId = '';



const uploadImage = async () => {
  const absolutePathToImage = Path.resolve('./image.png');
  const fileStream = await fs.createReadStream(absolutePathToImage);

  const streamClient = stream.connect(apiKey, apiSecret, apiAppId);
  const result = await streamClient.images.upload(fileStream);

  return result
}

const client = stream.connect(apiKey, apiSecret, apiAppId);
```

Produces the same error message: 
```
Argument of type 'ReadStream' is not assignable to parameter of type 'string | Buffer | File | ReadStream'.
  Type 'ReadStream' is missing the following properties from type 'ReadStream': isRaw, setRawMode, isTTY, write, and 25 more.ts(2345)
```

Am using default `tsconfig.json` produced by `npx tsc --init` 


Happy to test other suggestions.
