### ISSUE TITLE
object is coming as string in feed instead of json. 

### ISSUE THREAD

**Issue by patidarmanoj10** [GetStream/stream-js#253]
var feed = await me.get({
    limit: 20,
    enrich: true,
    reactions: { own: false, counts: true, recent: true }
  })

Actual output:
"latest_reactions": {},
"latest_reactions_extra": {},
"object": "{'a':'b'}",
"origin": null,
"reaction_counts": {},

expect output
"object": {"a":"b"} . ( this should be json instead of string )

**Comment by mircea-cosbuc** [comment]
Can you share how you are creating your activities? As per docs, the `object` is expected to be a string https://getstream.io/docs/#adding-activities.
