### ISSUE TITLE
removeActivity by foreignId doesn't compile after updating to version 4.2.4

### ISSUE THREAD

**Issue by MJRasmussen** [GetStream/stream-js#255]
After I recently updated getstream from version 4.2.2 to version 4.2.4, removeActivity by foreignId doesn't compile.

The documentation looks (still) like this: `user1.removeActivity({foreignId: 'tweet:1'});`

_Version 4.2.2:_
removeActivity(activityId: string | **object**): Promise<object>;

_Version 4.2.4:_
removeActivity(activityId: string | **Activity**): Promise<object>;

Changing it to Activity, now made **actor**, **verb** and **object** required.

Does this means that you don't support deleting by foreignId anymore or should i just insert empty strings in the required arguments?

**Comment by tbarbugli** [comment]
removing by foreign_id is still supported, unfortunately the typescript annotation in this case in incorrect

**Comment by mircea-cosbuc** [comment]
This should be fixed in https://www.npmjs.com/package/getstream/v/4.2.5.
