### ISSUE TITLE
Get all feeds added to feed group

### ISSUE THREAD

**Issue by wojteklu** [GetStream/stream-js#257]
Hi, 

Is it possible to get all feeds added to feed group? Thanks!

**Comment by tbarbugli** [comment]
Stream APIs don't support listing feeds at the moment, in most integrations this is not really needed since feeds don't need to be created upfront. What's your use case for this?

**Comment by wojteklu** [comment]
@tbarbugli Thanks for the help! My case is getting all feeds for moderator, but I will handle it in other way. Thanks!
