### ISSUE TITLE
Typescript typing conflicts with stream-chat

### ISSUE THREAD

**Issue by amakhrov** [GetStream/stream-js#258]
**Steps to reproduce**
- create a new TS app (I use angular, so initialized everything with `ng new`)
- add `getstream` and `stream-chat` dependencies
- import stream-chat first, then getstream in your app (order matters!)
```
import 'stream-chat';
import 'getstream';
```
- try to compile the app

**Result**
The following error is printed, failing the compilation:
```
ERROR in node_modules/getstream/types/getstream/index.d.ts(12,11): error TS2694: Namespace '"/Users/amakhrov/getstream-ts/node_modules/stream-chat/types/stream-chat/index"' has no exported member 'Client'.
```

**Suggested fix**
I guess that a fix could be to replace the reference to `stream` namespace with direct type reference inside getstream typings file: https://github.com/GetStream/stream-js/blob/cde5194af6346a3f1cd7368a905e977f97ff8510/types/getstream/index.d.ts#L12

Or perhaps, change to using a unique  namespace in each repository - as a more robust long-term approach.

**Comment by tbarbugli** [comment]
thank you for reporting this!

**Comment by johnfewell** [comment]
Hello there, I am facing this bug, what should I do?

**Comment by amakhrov** [comment]
@johnfewell changing the order of imports solved it in my project

**Comment by johnfewell** [comment]
@amakhrov Thank you for your help, changing the order does not help for me. There's only one service in my app that imports both packages. I changed the order and moved them around, same compile issue.

**Comment by tschellenbach** [comment]
ok, going to bump this internally, obviously not good

**Comment by johnfewell** [comment]
Thanks for taking action so swiftly!

**Comment by amakhrov** [comment]
Thanks for fixing it guys!
