### ISSUE TITLE
How I could retrieve Followers and Following count?

### ISSUE THREAD

**Issue by cbedoy** [GetStream/stream-js#260]
Currently you have the options of:

```
// List followers, following
feed.followers({limit: '10', offset: '10'});
feed.following({limit: '10', offset: '0'});
```

But it is returning an object like I expect you are handling limit and offset because it has reference about feed_id, target_id, updated_at: 

```
 {
  "duration": "2.66ms",
  "results": Array [
    Object {
      "created_at": "2019-08-22T17:53:54.4556937Z",
      "feed_id": "user:2845fe481e74b9010a7913d7b214a8937972d6b1",
      "target_id": "user:78839b4928305dceae5cfc626ce005592356666e",
      "updated_at": "2019-08-22T17:53:54.4556937Z",
    },
    Object {
      "created_at": "2019-08-21T18:42:55.631971587Z",
      "feed_id": "user:2845fe481e74b9010a7913d7b214a8937972d6b1",
      "target_id": "user:ad5d73f4ef30992f0abb2c0bc7414d7955dfce9d",
      "updated_at": "2019-08-21T18:42:55.631971587Z",
    },
  ],
}
```

_But is possible to have following and followers count avoiding pagination like?_

```
feed.followersCount();
feed.followingCount();
```

**Comment by Mastermindaxe** [comment]
Afaik this isn't supported by the REST API. See [this link](https://getstream.io/docs_rest/#followers). I'm only now getting started with stream, but I was asking myself the same question. Another thing is that it is only returning the last 1000 results. So there is no way to get an accurate representation of the follower count of a stream.
(Correct me if I'm wrong)

**Comment by Mastermindaxe** [comment]
Another thing that I'd like to point out (which I don't know if it's important) is that this imposed limit by the streams API is not described in the docs and could lead to confusion if working solely on this library rather than on the documentation on [Stream](getstream.io)

**Comment by mahboubii** [comment]
> Afaik this isn't supported by the official Stream REST API. See [this link](https://getstream.io/docs_rest/#followers). I'm only now getting started with stream, but I was asking myself the same question. Another thing is that it is only possible to return the last 1000 results. So there is no way to get an accurate representation of the follower count of a stream.
> (Correct me if I'm wrong)

You are correct, the following/follower count is computed only on user feeds for situations where you query a user profile, but not the feeds, it stops counting when it reaches 1000 following/follower, also as it is pointed out in the docs, you can only read [1000](https://getstream.io/docs/following/?language=js#reading-feed-followers) follows. 
You can use your own database to track these numbers and possibly keep track of all follow relationships if you have a use case for it. Let me know if you had any questions.

**Comment by ferhatelmas** [comment]
@Mastermindaxe we will expose a stat API which will return the counts directly (up to 10K in the beginning and we will increase gradually).

For the docs, please go ahead and give me the link of the page, I will document it there.

**Comment by Mastermindaxe** [comment]
> @Mastermindaxe we will expose a stat API which will return the counts directly (up to 10K in the beginning and we will increase gradually).
> 
> For the docs, please go ahead and give me the link of the page, I will document it there.

I'm talking about the inline documentation in this library, not about the official documentation. All is well there :D
The line I'm talking about is linked [here](https://github.com/GetStream/stream-js/blob/master/src/feed.ts#L402). It would be handy to see directly in documentation that there is a limit. I can imagine some users getting frustrated because they are referring to the in-library docs and not to the documentation page on getStream

**Comment by Mastermindaxe** [comment]
@ferhatelmas Thanks for the swift reply. Excited for this feature!
