### ISSUE TITLE
Get total all unseen count if more than 100

### ISSUE THREAD

**Issue by muthupriya** [GetStream/stream-js#266]
We have a Notification Feeds type of timeline.
we can only get unseen count maximum of 100. can we get total unseen count eventhough if it is more than 100. we just want overall total count.
How can we get this? can you please guide us?

```
feed = client.feed('activity_you_notify', '3');
    Promise.resolve(feed.get()).then(function (value) {
     
    }, function (err) {
      
    });
```

From Response, we are always get 100. we shouldn't get 101,102,103 unseen counts
"unseen": 100

Here is stackoverflow link.
https://stackoverflow.com/questions/58872196/from-getstream-total-unseen-count-not-getting-more-than-100

**Comment by tbarbugli** [comment]
closing this one; this not really an SDK question but an API/Product question (SO is a better place for that)
