### ISSUE TITLE
Support Node 13

### ISSUE THREAD

**Issue by feimosi** [GetStream/stream-js#273]
Currently when using node v13 we get the following error:

```sh
error getstream@4.3.0: The engine "node" is incompatible with this module. Expected version ">=4.8 <=12". Got "13.5.0"
```

**Comment by tbarbugli** [comment]
this was fixed on master but not yet released; can you try the latest (4.4.0)?

**Comment by feimosi** [comment]
Yes, I can confirm that with 4.4.0 it works perfectly fine.

**Comment by tbarbugli** [comment]
glad to hear that!

**Comment by rajeshwarpatlolla** [comment]
Try `yarn install --ignore-engines`
