### ISSUE TITLE
`addMany` should also run `replaceStreamObjects` over activity

### ISSUE THREAD

**Issue by andreyvital** [GetStream/stream-js#279]
Currently it's breaking my data that contains refs to collections' objects.

https://github.com/GetStream/stream-js/blob/master/src/lib/batch_operations.js#L29 vs https://github.com/GetStream/stream-js/blob/master/src/lib/feed.js#L94

**Comment by tbarbugli** [comment]
thank you for reporting this; can you try calling `replaceStreamObjects` on the activities param (replaceStreamObjects scans lists automatically so just replaceStreamObjects(activities) should be enough)?

**Comment by andreyvital** [comment]
`replaceStreamObjects` is not exported AFAIK.

**Comment by jaapbakker88** [comment]
@tbarbugli do we want to export  `replaceStreamObjects`?

**Comment by andreyvital** [comment]
Well ideally you'd handle that internally @jaapbakker88—I don't see any reason for running that myself on every place that I flush out activities. Thoughts?

**Comment by tbarbugli** [comment]
I was suggesting to try this out as a quick remediation; I agree this should be fixed internally.

**Comment by ferhatelmas** [comment]
#326
