### ISSUE TITLE
 loading multiple results - the callback doesn't have a result argument, works differently than subscribing to a feed

### ISSUE THREAD

**Issue by reduxdj** [GetStream/stream-js#28]
Here's an example of how I get the request for the feed to work, it should come back in the argument of the callback result argument, here's how i have to get the result, this works differently than subscribing to  a feed:

 UserFeedCollection.prototype.subscribeToFeed = function() {
    return this.me.subscribe((function(_this) {
      return function(data) {
        return _this.addOneAtIndex(data, 0);
      };
    })(this));
  };

 UserFeedCollection.prototype.fetch = function(lastSeenId) {
    var xmHttpR;
    this.lastSeenId = lastSeenId != null ? lastSeenId : 0;
    if (this.lastSeenId !== 0) {
      this.me.get({
        limit: this.pageLimit,
        mark_seen: true
      });
    } else {
      this.me.get({
        limit: this.pageLimit,
        id_lt: this.lastSeenId
      });
    }
    xmHttpR = this.me.get({
      limit: 10,
      mark_seen: true
    });
    xmHttpR.onload = (function(_this) {
      return function(data) {
        var item, list, _i, _len, _ref, _ref1, _results;
        list = data != null ? (_ref = data.target) != null ? (_ref1 = _ref.body) != null ? _ref1.results : void 0 : void 0 : void 0;
        if (!list) {
          return _this.trigger('sync');
        }
        _results = [];
        for (_i = 0, _len = list.length; _i < _len; _i++) {
          item = list[_i];
          console.log('item', item);
          _results.push(_this.addOne(item));
        }
        return _results;
      };
    })(this);
    return this.trigger('sync');
  };

**Comment by dwightgunning** [comment]
Yikes. This is exceptionally old. I hope you were able to resolve the issue through another channel; my  apologies if not - do let me know if there's something I might do to help you out from here.
