### ISSUE TITLE
ID, user names can't contain special characters

### ISSUE THREAD

**Issue by vtereshyn** [GetStream/stream-js#291]
Good day,

I'm trying to start using Getstream.io in my application and during the investigation, I get an error when I try to pass my `userId` into method that your API provides. You don't allow to use special characters in `userId`, but we use Auth0 and Auth0 generates ids for us like `auth0|something`. So `|` is not allowed. I'm wondering if you can help me with how to deal with that. I am not able to replace that special character every time when I work with stream API.

Thank you in advance,
Vlad

**Comment by vtereshyn** [comment]
Sorry, any updates here?

**Comment by ferhatelmas** [comment]
@vtereshyn thanks for reminder, appreciated. Was slipping otherwise. I will give you an update tomorrow with the progress.

**Comment by ferhatelmas** [comment]
@vtereshyn after checking internal usage, unfortunately, it has a special meaning for us. That's why it can't be permitted. Suggestion is to replace it with a dash (`-`).

**Comment by vtereshyn** [comment]
@ferhatelmas thanks for the update. Yeah, I see your point, but I have to do it in many places. This can cause a lot of unhandled errors in the future. I will think about how to deal with that. Thanks again!
