### ISSUE TITLE
Friends and Groups

### ISSUE THREAD

**Issue by creativeedge** [GetStream/stream-js#298]
Is there a method to initiate an invite/friend request.  Is there a method to create a group feed where an invite set of users can share and interact with same feed?

**Comment by ferhatelmas** [comment]
Invites aren't supported but it can be modeled via feeds actually where business logic runs on your side and you use the feed as a data store.

If you explain your use case, I might be able to help better.

**Comment by creativeedge** [comment]
> Invites aren't supported but it can be modeled via feeds actually where business logic runs on your side and you use the feed as a data store.
> 
> If you explain your use case, I might be able to help better.

Awesome.  Thanks for response and offer.  That's what I figured after I did a little more research.  I will definitely take you up on a recommendation shortly here.  I appreciate that.

**Comment by ferhatelmas** [comment]
Great, closing this to be clean. Feel free to open when you have more.
