### ISSUE TITLE
replace request with axios

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/stream-js#307]
request is now deprecated https://github.com/request/request/issues/3142

**Comment by ferhatelmas** [comment]
@mksglu can be a good exercise to modernize a good base and use more async/await along the way if you're up to challenge.

**Comment by mksglu** [comment]
> @mksglu can be a good exercise to modernize a code base and use more async/await along the way if you're up to challenge.

Yes, I am up for it and I will address as soon as possible. I will also update you with the progress as I go.
