### ISSUE TITLE
Unable to link user to activity using the user's reference

### ISSUE THREAD

**Issue by joelclouddistrict** [GetStream/stream-js#310]
We are unable use the user's reference when adding an activity on server-side:

We expect to be able to do:

``` javascript
feed.addActivity({
  actor: client.user(user.id),
 ...other_fields
});
```

As the docs show: https://getstream.io/docs/auth_and_permissions/?language=js&q=reference#permissions

But because of the `Activity` object typing, the `actor` fields expects an string, so it doesn't allow to use `client.user(username)`

How can we link the activity with the user?

We are using version 4.5.1 of the library

**Comment by ferhatelmas** [comment]
#334
