### ISSUE TITLE
Bad feed slug does not set err callback argument on follow

### ISSUE THREAD

**Issue by msamblanet** [GetStream/stream-js#32]
Accidentally typed the name of my feed slug in incorrectly and did not get the behavior I expected...

```
var stream = require("getstream");
var client = stream.connect("REDACTED", "REDACTED");
var aggregated1 = client.feed("agggggregated", "1");
aggregated1.follow("user", "1", function(err, resp, body) {
    console.log("Err: ", err);
    console.log("Body: ", body);
});

```

This gives me the following output:
```
Err:  null
Body:  { code: 6,
  detail: 'The following feeds are not configured: \'agggggregated\'',
  duration: '13ms',
  exception: 'FeedConfigException',
  status_code: 400 }
```
With some different slug names, different errors can result (I tried "does-not-exist" for testing and it gave a 404 instead of 400)

I would have expected the API to return an error (via the err arguments in the callback).  

I have not assessed deeper yet but I suspect other APIs have similar issues.

**Comment by tbarbugli** [comment]
this needs to be fixed at API level
