### ISSUE TITLE
Error: ETIMEDOUT

### ISSUE THREAD

**Issue by muthupriya** [GetStream/stream-js#338]
Error: ETIMEDOUT
    at StreamApiError.ErrorAbstract (/var/task/node_modules/getstream/lib/lib/errors.js:18:11)
    at new StreamApiError (/var/task/node_modules/getstream/lib/lib/errors.js:84:17)
    at Request.task [as _callback] (/var/task/node_modules/getstream/lib/lib/client.js:297:16)
    at self.callback (/var/task/node_modules/getstream/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Timeout.<anonymous> (/var/task/node_modules/getstream/node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  error: undefined,
  response: undefined

sometimes am getting  this timeout issue. after few minutes its working fine. can anyone help me?

**Comment by tbarbugli** [comment]
do you get this in production or in development? please make sure you are using an app on a region close by your servers/dev environment and to configure your client correctly (the api region must be passed to the client at init)

**Comment by muthupriya** [comment]
@tbarbugli  yes am getting from production getstream app. Also our server location is us-east-1. In getstream app also i had chosen us-east. Also stream connection i had used location
var client = stream.connect(APPKEY, APPSECRET, APPID, { location: APPLOCATION });

**Comment by muthupriya** [comment]
{ Error: Error: socket hang up
    at StreamApiError.ErrorAbstract (/var/task/node_modules/getstream/lib/lib/errors.js:18:11)
    at new StreamApiError (/var/task/node_modules/getstream/lib/lib/errors.js:84:17)
    at Request.task [as _callback] (/var/task/node_modules/getstream/lib/lib/client.js:297:16)
    at self.callback (/var/task/node_modules/getstream/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.onRequestError (/var/task/node_modules/getstream/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketCloseListener (_http_client.js:373:11)
    at TLSSocket.emit (events.js:203:15)
    at _handle.close (net.js:607:12)
  error: undefined,
  response: undefined,

sometimes am getting this issue also

**Comment by ferhatelmas** [comment]
@muthupriya you can also increase the timeout with the new version 

```
var client = stream.connect(APPKEY, APPSECRET, APPID, { location: APPLOCATION, timeout: 20000 });
```

**Comment by Andrei-Vakulski** [comment]
@muthupriya just got the same issue.
@tbarbugli @ferhatelmas what is the default value of `timeout`?

**Comment by ferhatelmas** [comment]
@Andrei-Vakulski `10s`

When did you get? File upload?

**Comment by Andrei-Vakulski** [comment]
@ferhatelmas no, just a regular user creation on node.js backend, something like `client.user(profileId).create()`.

**Comment by ferhatelmas** [comment]
OK, it's possible since network can create unbounded delay. Mine was an educated guess.

Please ensure: 
* setting the correct region in client setup
* setting good enough timeout for network / location

**Comment by Andrei-Vakulski** [comment]
Thanks, we'll investigate it deeper.
BTW, current README says that it is possible to configure `us-west`:

`javascript
// Optionally supply the app identifier and an options object specifying the data center to use and timeout for requests (15s)
const client = connect('YOUR_API_KEY', 'API_KEY_SECRET', 'APP_ID', { location: 'us-west', timeout: 15000 });
`
but [docs](https://getstream.io/docs/performance/?language=js) say that there are only 4 regions and there is no `us-west` listed.

So I believe if we are building US based app we should specify us-east?

**Comment by ferhatelmas** [comment]
That (`us-east`) is correct and default. That region (`us-west`) is wrong, I will update it.

**Comment by Andrei-Vakulski** [comment]
@ferhatelmas got it. Thanks!

**Comment by ferhatelmas** [comment]
updated at https://github.com/GetStream/stream-js/commit/ffd6abb7567aae49089830af1a13a8138f249ff3

**Comment by feimosi** [comment]
@ferhatelmas we're also experiencing this issue (`socket hang up`). I already tried setting region explicitly, increasing timeout etc. but nothing helped. It only happens on the notifications feed, during fetching data (though we use it most exhaustively).
It roughly occurs on less than 10% of the requests, rather randomly, on both local dev and production environments. The app runs on node v14.

**Comment by b3nni97** [comment]
@feimosi same on aws lamda

**Comment by ferhatelmas** [comment]
@b3nni97 I guess you caching the client. If so, you could test `keepAlive: false`. I believe your connection is gone when client comes back.

@feimosi Is there a caching ongoing in your case too?

**Comment by feimosi** [comment]
If caching is enabled by default then probably yes (we use the default config).

**Comment by ferhatelmas** [comment]
In short, if you use keepAlive, you need to wrap your call into a try/catch and handle it or retry. If no keep alive, I wouldn't expect you to see it. Please let me know by playing with that config.
