### ISSUE TITLE
How to get total result count on following / follows?

### ISSUE THREAD

**Issue by mwawrusch** [GetStream/stream-js#34]

**Comment by tbarbugli** [comment]
Hi,

Both ```followers``` and ```following``` feed methods return the total counts (as well as the requested resource with pagination). Let me know if you are having issues with that.

**Comment by mikberg** [comment]
@tbarbugli Is this still true? I can't seem to get a count.

```js
{ duration: '39ms',
  results:
   [ { created_at: '2016-10-27T12:00:39.170Z',
       feed_id: 'UserTimeline:auth0__57b6f2123123123',
       target_id: 'User:google-oauth2__11461121312323',
       updated_at: '2016-10-27T12:00:39.170Z' } ] }
```

**Comment by tbarbugli** [comment]
it's not, counters are not exposed by the APIs. Going to remove the misleading reply from history.
