### ISSUE TITLE
How to view feeds of other users without subscriptions

### ISSUE THREAD

**Issue by ezimnitskiy** [GetStream/stream-js#344]
We need to be able to show the feeds of all users separately from each other without using a secret key. How to do it? We would not want to do the implementation on the server and receive user feeds through our server as through a proxy

**Comment by shodgetts** [comment]
Hello, you need to enable a global read permission for a feed group. Please follow these instructions 

https://getstream.io/docs/auth_and_permissions/?language=js&q=global#permissions

**Comment by ferhatelmas** [comment]
We can add more customized permissions to your app too. If so, please write to support for your needs.
