### ISSUE TITLE
v5: 401 api_key is missing

### ISSUE THREAD

**Issue by alexabidri** [GetStream/stream-js#346]
Hi getstream team,

Since the last update to v5.0.0, I got issue when retrieving feed_activity, with 401 status code `api_key is missing`.

I checked the breaking changes, I didnt find anything to change in my codebase.

```js
  const getStreamClient = stream.default.connect(
    getStreamConfig.apiKey,
    getStreamConfig.apiSecret,
    getStreamConfig.apiId,
    { location: getStreamConfig.location },
  );

getStreamClient.feed(correlationType, correlationId);

await entity.get(JSON.parse(metadata));
```

**Comment by mahboubii** [comment]
hey @alexabidri, could you share the error stack or API response? 

do you happen to have `api_key` passed as options to `feed.get`? something like:
`getStreamClient.feed(correlationType, correlationId).get({api_key:null})`

**Comment by ferhatelmas** [comment]
Relevant snippet is as following, 
```
params: {
  api_key: this.apiKey,
  location: this.group,
  ...(kwargs.qs || {}),
},
```

if metadata in your snippet has `apiKey` as null, it will override.

**Comment by alexabidri** [comment]
I am only passing api_key, api_secret, app_id and location at startup of my service  with `stream.connect`

```js
  const getStreamClient = stream.default.connect(
    getStreamConfig.apiKey,
    getStreamConfig.apiSecret,
    getStreamConfig.apiId,
    { location: getStreamConfig.location },
  );

const metadata = {
   reactions: { own: true, recent: true, counts: true },
   limit: 5,
   id_lt: 'e561de8f-00f1-11e4-b400-0cc47a024be0',
}

getStreamClient.feed(correlationType, correlationId);

await entity.get(metadata);
```
My metadata object has only query fields related to get information from the getStream api. I don't use the get() function to pass authentication and authorization params, this should be done at service init.

Some error stack:

`"message":"{\"detail\":\"api_key is missing\",\"status_code\":401,\"code\":2,\"exception\":\"ApiKeyException\",\"duration\":\"0.00ms\"} with HTTP status code 401"`

`"error":{"detail":"api_key is missing","status_code":401,"code":2,"exception":"ApiKeyException","duration":"0.00ms"}
`

**Comment by ferhatelmas** [comment]
@alexabidri what is your app id?

**Comment by alexabidri** [comment]
@ferhatelmas My app id is "62246"

I will keep using the version 4 for now, I am fine with it. But hope It can help your team to find a potential issue for the new version.

Thanks :muscle:

**Comment by ferhatelmas** [comment]
@alexabidri Thank you for your help. 

One last bit, are you sure if `getStreamConfig.apiKey` contains your key correctly?

I also saw some successful requests for this app with the new version. Have you made it or a colleague?

**Comment by alexabidri** [comment]
I rollbacked the v5 this morning, I was just testing for 1 hour.

Yeah, getStreamConfig.apiKey has the key correctly, when I downgrade the version without changing the code, it works back again

**Comment by mahboubii** [comment]
@alexabidri could you try to log the request and put it here

```
try {
  getStreamClient.on('request', console.log);
  await entity.get(metadata);
} catch (err) {
  console.log('res', err.response);
}

```

**Comment by alexabidri** [comment]
@mahboubii  If u dont mind, I will try tomorrow as I am on another task and I am working in Asia, already end of day 😅

**Comment by alexabidri** [comment]
@mahboubii The issue is here https://github.com/GetStream/stream-js/blob/master/src/lib/client.js#L357

```js
this.apiKey = "API_KEY" // Api key from the stream client instance

kwargs.qs = {
  limit: 5,
  id_lt: null,
  api_key: null, // api_key is null at this moment because we dont pass it to the get() function
  withOwnReactions: true,
  withRecentReactions: true,
  withReactionCounts: true
}

const abc = {
   api_key: this.apiKey,
   location: this.group,
  ...(kwargs.qs || {}),
}

console.log(abc) => {
  api_key: null,
  location: 'unspecified',
  limit: 5,
  id_lt: null,
  withOwnReactions: true,
  withRecentReactions: true,
  withReactionCounts: true
}
```
The 4.5.4v is working fine https://github.com/GetStream/stream-js/blob/v4.5.4/src/lib/client.js#L493

By using the object spread operator like this, you will erase the api_key with from the client instance with `null`

**Comment by alexabidri** [comment]
> Relevant snippet is as following,
> 
> ```
> params: {
>   api_key: this.apiKey,
>   location: this.group,
>   ...(kwargs.qs || {}),
> },
> ```
> 
> if metadata in your snippet has `apiKey` as null, it will override.

My bad you are right, I discussed with my frontend colleague, he was sending the api_key at some calls. This issue can be closed, sorry guys!
