### ISSUE TITLE
How to get all activities?

### ISSUE THREAD

**Issue by delpin** [GetStream/stream-js#35]
Hello, could you help me with this problem:
- I try to get all activities ( command:  feed.get() ). When i get the response, i can't parse it ( can see it in console, but when i try to parse it in JS, the response is undefined )

**Comment by tbarbugli** [comment]
feed.get() requires a callback function

```
feed.get(function(error, response, body) { /* callback */ })
```

**Comment by delpin** [comment]
Thanks a lot! A little more question:
- How to change a number of activities in response?  In callback, when person do post(for example), or i do feed.get(), i have an array for 15 elements, how can i change the number of activities in array?

**Comment by tbarbugli** [comment]
have a look at the examples here: https://github.com/GetStream/stream-js/blob/master/README.md
