### ISSUE TITLE
createUserToken not working in rules on Auth0

### ISSUE THREAD

**Issue by iamsahu** [GetStream/stream-js#352]
I am trying to execute the following code in rules on Auth0

```
function (user, context, callback) {
  // TODO: implement your rule
  // createUserToken

  const stream = require('getstream');
  const client = stream.connect('YOUR_API_KEY', 'API_KEY_SECRET');
  const userToken = client.createUserToken(user.user_id);
  context.idToken['stream']=userToken;
  return callback(null, user, context);
}
```
But I am getting the following error: ERROR: client.createUserToken is not a function

This is happening on the test data itself.

gz#4501

**Comment by ferhatelmas** [comment]
Which version are you using ?

If you're on `5.0.0`, you need to update the line such that `const stream = require('getstream').default;

`5.0.1` should work without changes.

**Comment by iamsahu** [comment]
I was able to solve it using
`
  const stream = require('getstream@4.2.2');
`
