### ISSUE TITLE
How to create/delete feed groups?

### ISSUE THREAD

**Issue by will-weiss** [GetStream/stream-js#359]
Hello!

Is there a provided method to create or delete feed groups via the API?

When creating a feed group using the GUI, a POST is made to `dashboard/api/app/$APP_ID/feed/` with a payload that looks like

```
{
  "app_id": $APP_ID,
  "slug": "some_feed_group",
  "type_slug": "flat",
  "pubsub": true,
  "id": "some_id",
  "ranking_methods": []
}
```

I don't see a corresponding method for the client or in the [Rest Docs](https://getstream.io/docs_rest/) to create a feed group or delete one via the API. My use case is to programmatically create/delete feed groups as part of setup/teardown for integration tests.

Thanks in advance!

**Comment by tbarbugli** [comment]
Feed groups can only be created/deleted from the user dashboard. A very simple solution that does not require cleaning up is to use a test prefix to your feeds. ie. prepend a prefix to all feed IDs used in your tests and make sure that every test run has a unique prefix (ie. uuidv4)

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/4609'>Zendesk ticket #4609</a>:<br><br>Hello, currently there isn't a programmatic way to manage feed groups, it is done through the Stream Dashboard.
