### ISSUE TITLE
err is always null when there are server side validation errors

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/stream-js#36]
client.feed('notification', id).addActivity({
    "actor": id2,
    "actorName": "abc",
    "verb": "follow"
  });
body:{
  "code": 5,
  "detail": "Please use actorname instead of actorName for your field name",
  "duration": "10ms",
  "exception": "CustomFieldException",
  "status_code": 400
}
err = null

**Comment by tschellenbach** [comment]
is this in the browser, node or parse cloud?

**Comment by stevebread** [comment]
This is in node

**Comment by matthisk** [comment]
It is really easy to fix this, the question is if we want to do this it could potentially break people their integration if we release it with a non major version.
