### ISSUE TITLE
getstream.js broken in Angular with 4.5.4->5.0.0 update

### ISSUE THREAD

**Issue by a10kiloham** [GetStream/stream-js#361]
Using this in angular the process variable is not defined, so it errors out. This comes from line 28 where checks were added ```if (process && process.env && process.env.STREAM_URL && !apiKey)```

#337 and #223 seems to introduce this - it would be preferable to check typeof the old way to keep Angular sane.

gz#4695

**Comment by tbarbugli** [comment]
thank you for reporting this!

**Comment by ferhatelmas** [comment]
@a10kiloham thanks for the report, please grab `v5.0.4`.

**Comment by a10kiloham** [comment]
Thanks for this super fast turnaround! I'm still getting a process not found error - I think there's prob one extra check missing - here's my error with Angular ```ERROR Error: Uncaught (in promise): ReferenceError: process is not defined
ReferenceError: process is not defined```

**Comment by ferhatelmas** [comment]
Let us check. Do you have any more information where it's coming from?

**Comment by a10kiloham** [comment]
Checking on it now! Will provide more info shortly

**Comment by egorpanok** [comment]
@ferhatelmas Let me step in. The error occurs here (taking the 5.0.4 version):
**node_modules/getstream/lib/getstream.js:59** (function connect(...)).

I'm not sure why but the **59th** line in the **lib** folder still has the old version of the code:

**if (process && process.env && process.env.STREAM_URL && !apiKey) {**

I tried both cleaning the npm cache and removing node_modules folder and re-installing the dependencies. But it still persists.
Can you advise how we can tackle this?

Kind Regards,
Egor

**Comment by mahboubii** [comment]
@a10kiloham @egorpanok Looks like we had a bad release, please bump to `v5.0.5` and hopefully, the issue is resolved.

**Comment by egorpanok** [comment]
@mahboubii  It works now! Perfect! Thank you very much!
@a10kiloham
