### ISSUE TITLE
TS error?

### ISSUE THREAD

**Issue by baileywall** [GetStream/stream-js#373]
Hi all, have started to integrate the TS into our code and noticed something that I think is a bug.

It seems like this line https://github.com/GetStream/stream-js/blob/master/src/feed.ts#L151 should actually be an array, rather than just a single EnrichedActivity.

Thanks!

gz#5712

**Comment by ferhatelmas** [comment]
@baileywall you're right, we will fix. PRs are also welcome if you want to take care.
