### ISSUE TITLE
followStats throws NotAllowedException

### ISSUE THREAD

**Issue by jpagand** [GetStream/stream-js#396]
On a server-side app and following the [documentation](https://getstream.io/docs/following/?language=js), I get an error trying to call `followStats`

Error:
```
{
    "detail": "You do not have permission to perform this action.",
    "status_code": 403,
    "code": 17,
    "exception": "NotAllowedException",
    "duration": "0.00ms",
    "more_info": "https://getstream.io/docs/api_error_responses"
}
```

Code to reproduce:
```
import getstream from 'getstream';

const client = getstream.connect(API_KEY, API_KEY_SECRET, APP_ID);
client.feed('user', 'me').followStats();
```

gz#7250

**Comment by ferhatelmas** [comment]
@jpagand Nothing seems wrong here. Could you pass your api key ?

**Comment by jpagand** [comment]
Api key: mh5hs94numkn

**Comment by jpagand** [comment]
Any update @ferhatelmas ?

**Comment by ferhatelmas** [comment]
@jpagand fixed in https://github.com/GetStream/stream-js/releases/tag/v7.0.1

**Comment by brandoniumNutrien** [comment]
seem to still have this problem
