### ISSUE TITLE
Wrong type for own_reactions in EnrichedActivity

### ISSUE THREAD

**Issue by hannojg** [GetStream/stream-js#397]
Hey,

`own_reactions` seems to have the same structure as e.g. `latest_reactions`. However, the `own_reactions` are said to be an array (while all other reaction records aren't). I believe that this is a mistake, compare for example:

Line 111: https://github.com/GetStream/stream-js/blob/2ebe896dbd25eab88e503249bf0ff77a724b150f/src/feed.ts#L111
and
Line 109: https://github.com/GetStream/stream-js/blob/2ebe896dbd25eab88e503249bf0ff77a724b150f/src/feed.ts#L109

thanks in advance for looking into this ✌️ 

gz#7333

**Comment by mahboubii** [comment]
@hannojg Thanks for reporting this.

**Comment by shodgetts** [comment]
Agent comment from ferhat elmas in <a href='https://getstream.zendesk.com/agent/tickets/7333'>Zendesk ticket #7333</a>:<br><br>This is released as 6.2.2
