### ISSUE TITLE
StreamFeed.removeActivity returns successful response but appears to remove the activity async.

### ISSUE THREAD

**Issue by shiivan** [GetStream/stream-js#403]
Repro Steps:
1) Using connected stream-js client, create an instantiated StreamFeed object.
```
const feed = streamClient.feed('some-feed-name', 'some-stream-user-id);
```
2) Find activity
```
const beforeRemoveResponse = await streamClient.getActivities({ ids: ['some-activity-id']});
```
3)
```
feed.removeActivity(beforeRemoveResponse.results[0].id);
```
4)
```
const afterRemoveResponse = await streamClient.getActivities({ ids: ['some-activity-id']});
```

Expected Behavior:
The `afterRemoveResponse` result is empty, as I've removed the activity and Stream gave me 200/OK Http response code.

Actual:
The activity is still there for some amount of time.

I guess this could be expected behavior or a result of caching, however it is undocumented and coupled with the fact that length of processing appears to vary from near instantaneous to minutes it is something that has sucked up some of my time and not friendly.

gz#7877

**Comment by shiivan** [comment]
Related, I can file a different bug if you find it useful.

If I delete the last remaining activity in an activity group and then ask the StreamFeed client for the ActivityDetail, I get a 200 but with data from an entirely different Activity.

Request:
```
await feed.getActivityDetail(
    '7e619f21-38dc-11eb-8080-800038395f4a.feedback:resolved_SO:3128c5591b194109aae44c0e1198cfc9-bba3a47470ec458596e780527d04fe6b_2020-12-07',
    {},
  );
```

Response:
```
{
  "results": [
    {
      "activities": [
        {
          "actor": "SU:3128c5591b194109aae44c0e1198cfc9-0296e630b50b62b41a5ab9797a04bdbf114",
          "foreign_id": "",
          "id": "80204172-3665-11eb-a9c2-0ae838defca7",
          "object": "SO:course:3128c5591b194109aae44c0e1198cfc9-1603913040600387a84dd7e8b431f8e4112d08e16193d",
          ...,
        }
      ],
      "activity_count": 1,
      "actor_count": 1,
      "created_at": "2020-12-04T19:18:33.418725",
      "group": "course:assigned_SO:course:3128c5591b194109aae44c0e1198cfc9-1603913040600387a84dd7e8b431f8e4112d08e16193d_2020-12-04",
      "id": "80212ef2-3665-11eb-8080-800135ddb1e9.course:assigned_SO:course:3128c5591b194109aae44c0e1198cfc9-1603913040600387a84dd7e8b431f8e4112d08e16193d_2020-12-04",
      ...,
    }
  ],
  "next": "/api/v1.0/feed/notifications_self/3128c5591b194109aae44c0e1198cfc9-0296e630b50b62b41a5ab9797a04bdbf114/?api_key=<redacted>&id_gt=80212ef2-3665-11eb-8080-800135ddb1e9.course%3Aassigned_SO%3Acourse%3A3128c5591b194109aae44c0e1198cfc9-1603913040600387a84dd7e8b431f8e4112d08e16193d_2020-12-04&limit=1",
  "duration": "7.29ms",
  "unseen": 0,
  "unread": 34
}
```

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/7877'>Zendesk ticket #7877</a>:<br><br>Hi,

Thank you for reaching out. We are looking into this for you and will be in touch shortly. In the meantime, could you please provide your AppID and the version of the Stream SDK you are using? Thanks!

Best,
Ryan

**Comment by shiivan** [comment]
Sure, we're v7.0.1 and the appId is 88356

**Comment by ferhatelmas** [comment]
@shiivan this is expected. Activity is removed from the associated feed so users can't get it but admin can always receive activities, they aren't removed.

**Comment by shiivan** [comment]
Hmm that is not the behavior I saw but I'll try again.

Do you have any comments on the false 200 response for an entirely different Activity?

**Comment by ferhatelmas** [comment]
I think there is a misunderstanding here. 

An activity can be added to multiple feeds so if it's removed from one of them, it doesn't mean it's deleted. When you fetch an activity, we can't return deleted flag on it because for example, it might be deleted from feed A but it might be used in feed B.

> false 200 response for an entirely different Activity

This shouldn't happen, if you have a specific one, please give details because it means a bug.

**Comment by shiivan** [comment]
Ah, that is my misunderstanding then.

For what I was seeing on the false 200.
https://github.com/GetStream/stream-js/issues/403#issuecomment-741149059

I am asking for a particular activity detail and get the details for another activity. Making this look like an index/list request and  less like a GET.

**Comment by ferhatelmas** [comment]
What you did in the snippet is receiving built `group id` for an aggregated/notification feed. That id is pseudo id generated from aggregation format. That's why activities inside a group is dynamic as new ones are coming and can be changed with ranking too. You don't want it in general because its usage very limited, IMHO.

Use real activity id or foreign id/time pair on client if you want to fetch specific activities. From your snippet, `80204172-3665-11eb-a9c2-0ae838defca7` is the id. `client.getActivities({ids: [your_id]})`
