### ISSUE TITLE
feed subscribe success but not callback any data when add new activity

### ISSUE THREAD

**Issue by vuthanhtrung0504** [GetStream/stream-js#404]
const callback = data => {
    console.log('data: ', data);
  };

  const successCallback = (data) => {
    console.log('now listening to changes in realtime');
  };

  const failCallback = data => {
    console.log(data);
  };

  feedUser?.subscribe(callback).then(successCallback, failCallback);
}

**Not return data in callback function after addActivity. This works before but in this afternoon it start not callback any data**

Ps: successCallback works well

gz#7942

**Comment by ferhatelmas** [comment]
Please recheck, it should be fine.

**Comment by vuthanhtrung0504** [comment]
@ferhatelmas i have rechecked it but it still not work yet

**Comment by vietvptpro** [comment]
Same issue

**Comment by ThangPh96** [comment]
I have the same issue :( pls check it

**Comment by ferhatelmas** [comment]
Could you confirm if it works for you now or not ?

**Comment by vuthanhtrung0504** [comment]
@ferhatelmas it just works now. Thanks for the support
