### ISSUE TITLE
Network Error while uploading an image

### ISSUE THREAD

**Issue by aamir-ans** [GetStream/stream-js#418]
@mahboubii I'm trying to upload image using **client.images.upload** but getting error  **Network Error**. All other functions are working.

Here are the module details:
  "getstream": "^7.2.1",
 "react-native-activity-feed": "^1.0.2"

kindly let me which stable version I can use.

gz#9044

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/9044'>Zendesk ticket #9044</a>:<br><br>Hi there,

Are you able to provide the full error? Also how large is the image?

**Comment by aamir-ans** [comment]
Hi,
Image is less than 150kb, 
see
client.images.upload("file:///storage/emulated/0/Android/data/com.***********/files/Pictures/d6871b3f-8446-471d-9527-062239e517b0.jpg","test", contentType).then(res=>{
                console.log('upload result :',res)
            }).catch(e=>{
                console.log('upload result error :',e.message);
            });
  Error :
  [Mon Feb 01 2021 23:27:08.959]  LOG    upload result error : Network Error

**Comment by mahboubii** [comment]
hey @aamir-ans, apparently there is an issue with the RN debugger catching network requests. Please try the upload without having the app in debug mode.

**Comment by ferhatelmas** [comment]
@aamir-ans what do you have in `contentType` ? Also, could you pass me your api key ?

**Comment by aamir-ans** [comment]
@mahboubii Checked on release mode as well facing same issue.
@ferhatelmas contentType=>  image/jpeg.
API key : htc3thmjubcr

**Comment by vishalnarkhede** [comment]
@aamir-ans Whats the version of react-native you are using? Also what version of Flipper are you on?

**Comment by aamir-ans** [comment]
@vishalnarkhede React native version =>  "0.62.1"

**Comment by vishalnarkhede** [comment]
@aamir-ans and flipper?

**Comment by aamir-ans** [comment]
@vishalnarkhede Hey I have not added any flipper other dependencies.

**Comment by vishalnarkhede** [comment]
Hey @aamir-ans react-native 0.62 comes with flipper by default. You can upgrade the version as mentioned here - https://github.com/facebook/flipper/issues/993#issuecomment-619823916

**Comment by aamir-ans** [comment]
Hey Vishal, how is this working when I'm using StatusUpdateForm as an
internal component using the same upload API ?

>

**Comment by vishalnarkhede** [comment]
@aamir-ans just to confirm, so it works for you on StatusUpdateForm? Then I am a little confused, as to whats the issue here? Can you please share some code around your upload logic?

**Comment by aamir-ans** [comment]
See I'm trying to upload same image that is uploaded via StatusUpdateForm, but facing network error issue in case of direct using API.

client.images.upload("file:///storage/emulated/0/Android/data/com.******/files/Pictures/c73f0c58-1e28-42c2-946b-1d4360c6203d.jpg","test", "image/jpeg").then(res=>{
                console.log('upload result ',res);
            }).catch(e=>{
                console.log('upload result error ',e.message);
            });
            
**[Tue Feb 02 2021 17:13:02.635]  LOG      upload result error  Network Error**

**Comment by mahboubii** [comment]
@aamir-ans can you try with undefined for file name? `client.images.upload(file_path, undefined, "image/jpeg")`

**Comment by aamir-ans** [comment]
@mahboubii Tried getting same error [Tue Feb 02 2021 18:23:30.733]  LOG      upload result error  Network Error

**Comment by aamir-ans** [comment]
@mahboubii @vishalnarkhede Image upload is working fine for iOS, this issue I'm facing in android

**Comment by aamir-ans** [comment]
@vishalnarkhede Any update ?

**Comment by vishalnarkhede** [comment]
@aamir-ans what are you using to pick the image? Is there any way to validate if the file exists at url `file:///storage/emulated/0/Android/data/com.******/files/Pictures/c73f0c58-1e28-42c2-946b-1d4360c6203d.jpg`

**Comment by vishalnarkhede** [comment]
If you can please share code around image picker functionality, that will be great.

**Comment by ferhatelmas** [comment]
Will close due to inactivity. Please let us know if you can provide more details to debug.

**Comment by habrahamyanmabbly** [comment]
Any updates ?

**Comment by tj-mc** [comment]
In my case I patched this myself. The content type is incorrect when uploading image on Android.
It is "image" but it needs to be "image/jpg".

In stream-chat/dist/browser.js I changed this line to have the content type hardcoded.

`var data = addFileToFormData(uri, name, 'image/jpg');`

**Comment by gabrielfurini** [comment]
I can confirm the issue still exists, so I think the issue might be reopened.
We are getting the error in 8.4.1 in Android, both development or release builds. iOS is OK though.

Our stack is Expo SDK 51 with RN 0.74.5.

We check actively if the file exists before calling the upload method.

Trying to call `client.images.upload(uri, undefined, "image/jpg");`, `client.images.upload(uri, "filename", "image/jpg");`, `client.images.upload(uri, undefined, "image/jpeg");` always returns a "Network Error".
The same happens when trying to upload a video using `client.files.upload()`.

Would you guys mind checking it @mahboubii @vishalnarkhede, please?
Thank you!

**Comment by Miloshinjo** [comment]
Same issue, android only, was there any solution for this? Cheers :)

**Comment by 386sx** [comment]
Same here.
