### ISSUE TITLE
No way to get individual notifications by activity group id

### ISSUE THREAD

**Issue by melissjs** [GetStream/stream-js#424]
Version: 5+
System: Node.js

When marking notifications read or seen by explicitly passing activity group ids, the response returns the 25 latest notifications, not the individual activity groups that were explicitly passed. Is there a way to retrieve notifications by activity group ids? I was not able to find the answer in the only notifications documentation I could find: [https://getstream.io/activity-feeds/docs/node/notification_system/?language=javascript](url) I have tried making the request from the client and directly; all of which ignore the ids and return 25 of the latest notifications when no limit is specified. 

Below are some examples of what I attempted:

`client.feed('notification', 'user_0f19dc70-a112-4fa5-9028-56f6f3d9xyzz').get({ ids: ['cfb6979b-7635-11eb-8080-800171da6072.comment_2021-02-24', 'c87d376a-7635-11eb-8080-8000499121a0.like_2021-02-24']})`

`client.feed('notification', 'user_0f19dc70-a112-4fa5-9028-56f6f3d9xyzz').get(ids = ['cfb6979b-7635-11eb-8080-800171da6072.comment_2021-02-24', 'c87d376a-7635-11eb-8080-8000499121a0.like_2021-02-24'])`

`client.feed('notification', 'user_0f19dc70-a112-4fa5-9028-56f6f3d9xyzz').get( 'cfb6979b-7635-11eb-8080-800171da6072.comment_2021-02-24', 'c87d376a-7635-11eb-8080-8000499121a0.like_2021-02-24')`

`https://api.stream-io-api.com/api/v1.0/enrich/feed/notification/user_0f19dc70-a112-4fa5-9028-56f6f3d9xyzz/?api_key=abcdefgkey&ids=cfb6979b-7635-11eb-8080-800171da6072.comment_2021-02-24,c87d376a-7635-11eb-8080-8000499121a0.like_2021-02-24`

I can't imagine there is no way to get them by id, please let me know if/where I overlooked the answer to this question. Thank you for your help on this.

gz#9690

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/9690'>Zendesk ticket #9690</a>:<br><br>Hi there,

We'll take a look as soon as we can.

**Comment by mahboubii** [comment]
@melissjs If you have the activityId, you can probably fetch the data using this function:

`client.getActivities({ids:[LIST_OF_IDS]})`

**Comment by melissjs** [comment]
@mahboubii thank you for your quick reply, it seems the _activity group ids_ error, I assume because this function is expecting actual activity ids. Is there any solution you can think of?
`{
  "detail": "invalid activity ID \"c87d376a-7635-11eb-8080-8000499121a0.like_2021-02-24\"",
  "status_code": 400,
  "code": 4,
  "exception": "InputException",
  "duration": "0.19ms",
  "more_info": "https://getstream.io/docs/api_error_responses"
}`

**Comment by ferhatelmas** [comment]
@melissjs That's correct. Actual ids or foreign ids are required in `client.getActivities`. Getting groups isn't supported.

If you want to operate in groups as a single activity, better to change aggregation function to put a single activity into a group such as `{{id}}`.
