### ISSUE TITLE
What's the difference between getstream & stream-chat?

### ISSUE THREAD

**Issue by AdityaAnand1** [GetStream/stream-js#427]
https://www.npmjs.com/package/getstream
https://www.npmjs.com/package/stream-chat

Both have identical descriptions and claim to be the latest JS client for stream chat 🙄

**Comment by ferhatelmas** [comment]
getstream:

> a web service for building scalable *newsfeeds and activity streams*.

getstream is [feeds](https://getstream.io/activity-feeds/) client and the other is [chat](https://getstream.io/chat/) client.

**Comment by shodgetts** [comment]
Hi @AdityaAnand1 👋  Seems like you might be having a little trouble getting started, or at least with our documentation. The support team would love to hear from you! While on a 30 day free trial or on our paid chat plans, you are welcome to email support@getstream.io with your technical issues. We're here to help!

**Comment by AdityaAnand1** [comment]
I'll do that, but I shouldn't have to 😄 

There are clearly obvious gaps in the documentation - outdated tutorials, incomplete/ambiguous docs etc.

My suggestion would be to get the tech/dev relations/content team at Stream to go over all their publicly accessible documentation once and ensure everything is consistent.

**Comment by tobiasbueschel** [comment]
Totally agree here with @AdityaAnand1, I think we could improve the naming of the repositories. Here would be my suggestion:

- https://github.com/GetStream/stream-chat-react/issues/769
