### ISSUE TITLE
getActivityDetail return wrong data

### ISSUE THREAD

**Issue by willdd56** [GetStream/stream-js#430]
I used "getActivityDetail" function to retrieve activity's detail but It always return another activity's data

gz#10097

**Comment by ferhatelmas** [comment]
Could you pass me apikey / activity id then describe what is different?
Maybe also share the snippet of your code how you call this endpoint ?

**Comment by ferhatelmas** [comment]
One more note, you might be using a wrong id such as a group id in aggregates. This endpoint works with a single activity and expects `UUID` generated by us unless you provided your foreign ID and time.

I will close this ticket for inactivity but if you need any issues, please reply and we will investigate further.
