### ISSUE TITLE
Feed.followStats don't work with custom token

### ISSUE THREAD

**Issue by hannojg** [GetStream/stream-js#436]
We are creating a feed like this in our clients:

```js
const feed = getstreamClient.feed(feedSlug, userId, `Bearer ${jwt}`);
```

and then call `followStats()` on this feed.
This doesn't work, as `followStats` doesn't consider the `this.token` var in the feed instance, so the `Authorization` header will be `null`:

https://github.com/GetStream/stream-js/blob/3b927229c13d69c43b3e7e0610f8b72714ef3927/src/feed.ts#L470

We fixed it by changing it to this:
```typescript
return this.client.get<FollowStatsAPIResponse>({
      url: 'stats/follow/',
      qs,
      token: this.client.getOrCreateToken() ?? this.token,
    });
```

However, I think that this should be handled differently (don't know enough about the getstream lib structure to put this in the correct place).

Thanks in advance 

gz#10327

**Comment by ferhatelmas** [comment]
```js
const feed = getstreamClient.feed(feedSlug, userId, `Bearer ${jwt}`);
```

Why do you need third parameter in this call ?

Moreover, `getOrCreateToken` will never be `nullish` so it won't fallback to `this.token`. When you say it was working, what was the issue / error ?

**Comment by hannojg** [comment]
its working with the changes. We need this third parameter, as the client isn't directly communicating with getstream but with a proxy service in our backend, which needs the authentication token from our system.

**Comment by hannojg** [comment]
The error was a 403, unauthenticated (which is returned by our proxy I assume), as the header field `Authentication` had the value `null`.

**Comment by hannojg** [comment]
getOrCreateToken can be null, look how we setup the client in the frotnend:

```js
const options: ClientOptions = {
  urlOverride: {
    api: Config.GETSTREAM, // our custom endpoint
  },
};

new StreamClient("1", null, undefined, options);
```

**Comment by ferhatelmas** [comment]
`new StreamClient("1", null, undefined, options);`

This client isn't functional and this usage looks rare. in this case, it can fallback to token and your change makes sense. However, what is the reason you initialize client this way ?

**Comment by ferhatelmas** [comment]
released in https://github.com/GetStream/stream-js/releases/tag/v7.2.5
