### ISSUE TITLE
BaseActivity type is inaccurate

### ISSUE THREAD

**Issue by goleary** [GetStream/stream-js#440]
I've noticed several instances where the types are not consistent with the way in which the docs suggest using this library:

[BaseActivity](https://github.com/GetStream/stream-js/blob/9c882c040b8f075072e7c7e95e72165147023f79/src/feed.ts#L65) only accepts a string for `actor`, but [the docs](https://getstream.io/activity-feeds/docs/node/enrichment/?language=javascript&q=foreign_id#collections-users) show using a `StreamUser` object.

gz#11235

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/11235'>Zendesk ticket #11235</a>:<br><br>Hi there,

Thanks for getting in touch, we'll take a look into this as soon as we can.

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/11235'>Zendesk ticket #11235</a>:<br><br>Hi

As you have figured it out, the `actor` accepts the string.


NAME TYPE DESCRIPTION DEFAULT
actor string the actor performing the activity -


Please refer to this doc for more details on creating an activity.

The example you saw was under collections where we had shown how to embed a user and an object inside an activity.


    const act = await feed.addActivity({ actor: client.currentUser,verb: "post",object: "post",});


is implied as


    const act = await feed.addActivity({ actor: "SU:"+ client.currentUser.id,verb: "post",object: "post",});


Resulting in -


    {  actor: 'SU:seetha',  duration: '8.29ms',  foreign_id: '',  id: '543aa93b-a18c-11eb-923f-128a130028af',  object: 'post',  origin: null,  target: '',  time: '2021-04-20T03:56:04.555603',  verb: 'post'}


We will update the docs wherever necessary.

Hope this helps.

Also kindly note that the Issue section of this Github repo is now reserved only for bug reports and feature improvements and suggestions. For this kind of support, we would suggest emailing our Customer Success and Engineer support team at support@getstream.io with your application key or ID and we’ll be able to help you out. Thanks for your understanding, we’re going to mark this issue as closed.

Cheers
Seetha

**Comment by goleary** [comment]
Just as an FYI, the docs appear to be correct as I can provide a `StreamUser` object and everything works as expected during runtime...I just have to tell TypeScript to shut up.
issue:
![image](https://user-images.githubusercontent.com/16123225/115336603-62180c00-a154-11eb-9592-aa51c4cb4c30.png)
gnasty workaround:

![image](https://user-images.githubusercontent.com/16123225/115336657-73611880-a154-11eb-81e7-398684cd6147.png)

**Comment by vjeranc** [comment]
Yeah, the guys that wrote this library have made it a bit difficult to use with TypeScript. Current types are a lot to process.

**Comment by mahboubii** [comment]
Thanks @goleary for reporting this issue. #440 should fix it.

**Comment by mahboubii** [comment]
@vjeranc The client should work without issues even if you use the default generic types. You can get a lot more back if you provide your data types when instantiating the client for the first time.

**Comment by goleary** [comment]
thanks!
