### ISSUE TITLE
Why are there 3 alternately formatted names for foreign id in the node sdk?

### ISSUE THREAD

**Issue by goleary** [GetStream/stream-js#442]
1. https://github.com/GetStream/stream-js/blob/9c882c040b8f075072e7c7e95e72165147023f79/src/feed.ts#L318
2. https://github.com/GetStream/stream-js/blob/9c882c040b8f075072e7c7e95e72165147023f79/src/feed.ts#L74
3. https://github.com/GetStream/stream-js/blob/9c882c040b8f075072e7c7e95e72165147023f79/src/client.ts#L109

It's rather confusing to have so many variations on the same variable.

Not to mention, for 3, the types want me to provide `foreignID` but when I do that I get a runtime error:
```
Error: {"detail":"\"foreignID\" is not a valid field","status_code":400,"code":4,"exception":"InputException","duration":"0.14ms","more_info":"https://getstream.io/docs/api_error_responses"}
```

So I have to use `//@ts-ignore` in order for my code to run...

Runtime only accepts `foreign_id`.

Linked to Zendesk issue 

gz#11238

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/11238'>Zendesk ticket #11238</a>:<br><br>Hi

Thanks for your feedback. Appreciate it.
We will look into this and update the docs, wherever necessary.
As you have figured it already, `foreign_id` is the correct usage.

Cheers
Stream Team

**Comment by goleary** [comment]
Thanks!

It's not the docs that need updating, it's the code 😬

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/11238'>Zendesk ticket #11238</a>:<br><br>Hi

Sure, thanks for your feedback. Appreciate it.
We will update the SDK accordingly.

Cheers
Stream Team

**Comment by mahboubii** [comment]
Hey @goleary, thank you for bringing this to our attention. #450 should fix the issue.

**Comment by goleary** [comment]
thanks for following up!
