### ISSUE TITLE
Handling activity tags / hashtags [TO]

### ISSUE THREAD

**Issue by faustoct** [GetStream/stream-js#448]
Hi there,

I can't handle multiple tags , which way is the proper one to handle hashtag / tag behavior?

```"to": ["tag:amsterdam", "tag:london"]``` or ```"to": ["tag:amsterdam,london"]```

thank you!

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/11395'>Zendesk ticket #11395</a>:<br><br>Hi

Thanks for reaching out to us.

We would use like this -
`"to": ["tag:amsterdam", "tag:london"]`

The feed slug is the combination _`feed_group`_`:`_`feed_id `_that constitutes the unique identifier of a given feed.

Cheers
Seetha<br><p><em><small>added by Git-Zen</small></em></p>

**Comment by faustoct** [comment]
thank you!
