### ISSUE TITLE
Add support for retrieving activities by foreign id or uuid

### ISSUE THREAD

**Issue by fearless23** [GetStream/stream-js#457]
We add activities in a serverless manner, i.e some async operation adds the activities, 
thus the activity id created by getstream is not useful in terms of retreiving activity

We use foreign_id concept to link our db with getstream activities.

I didnt found any way to get activities by foreign_id.

Suggestion: In Getstream chat, user can specify message.id when creating a message and later get by message id. Can same be  done for feeds as well.

Am i missing something here

gz#12616

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/12616'>Zendesk ticket #12616</a>:<br><br>Hi

Thanks for reaching out to us.
The team will look into this as soon as possible.

In the meantime, you can make use of this -

`await client.getActivities({ids: [activity_id1, activity_id2]})`

Cheers
Seetha
<br><p><em><small>°°°</small></em></p>

**Comment by mahboubii** [comment]
hey @fearless23, you can use the combination of the [foreign id and time](https://getstream.io/activity-feeds/docs/node/adding_activities/?language=javascript#uniqueness-foreign-ids) to get/update activities.

**Comment by royscheepens** [comment]
Hi @mahboubii the docs you linked to only mentions _updating_ an activity by foreign_id & time. How would one use a foreign_id & time combination to _get_ a single activity?

**Comment by mahboubii** [comment]
You can [getActivities](https://github.com/GetStream/stream-js/blob/main/src/client.ts#L806) like this: 
`client.getActivities({foreignIDTimes: [{foreign_id: ..., time: ...}, ...]})`

**Comment by royscheepens** [comment]
Thanks! I just found out about the `client.getActivities` method, you kinda need to dig into the docs to find it. Maybe an idea to also mention it [here](https://getstream.io/activity-feeds/docs/node/adding_activities/?language=javascript&q=getActivities#retrieving-activities). Fetching activities by foreign_id is quite a common use-case I think, and it is not immediately apparent in the docs how to do it. 

Awesome product btw! I'm having a blast integrating it into my app :)

**Comment by fearless23** [comment]
@mahboubii thanks and btw great product.
