### ISSUE TITLE
Clarity on `getOrCreate`

### ISSUE THREAD

**Issue by chris-williams-efr** [GetStream/stream-js#458]
I've read through the SDK, and the documentation for the underlying REST api (https://getstream.io/docs_rest/#user).. 

When using `User(someId).getOrCreate({ ... })`, if the user already exists, is it's data changed with at passed in this payload?  From my experience, it is - but I don't think this is the expected behaviour.   It should ether create a user with the payload, or return a user with it's current payload. 

Could we get clarification that this is the expected behaviour in the documentation please, if that is the case.

gz#12626

**Comment by chris-williams-efr** [comment]
Don't you just hate it when, after asking for help, you realise it's your problem after all? 🤡  I was reading from the wrong part of the data structure. 

However, the clarification in the documentation would be appreciated still, as I've been hunting the docs to see if it should or should not modify the user data on `getOrCreate`,  in the JS SDK or the underlying REST API. 

Thanks,

**Comment by SeniYG** [comment]
Hi Chris,

😄 No worries, we're glad you could solve your issue.
Thanks for the feedback, I'm passing this on to our documentation team to help with clarifying this on the docs.

Best,
