### ISSUE TITLE
Analytics Engagement not implemented

### ISSUE THREAD

**Issue by victorkurauchi** [GetStream/stream-js#460]
Hi team, I'm looking into implement the trackEngagement in my project, however I can't really find the API available for engagements. Any ideas if it's really not possible to use the engagement with this library?

No occurrences found for `trackEngagement()` in the repo.
![image](https://user-images.githubusercontent.com/2061031/124238021-82544600-db5b-11eb-8817-9a7c318a235c.png)

https://getstream.io/activity-feeds/docs/javascript/analytics_engagements/?language=javascript#tracking-engagements

```
const engagement = { 
  // the label for the engagement, ie click, retweet etc. 
  'label': 'click', 
  // the ID of the content that the user clicked 
  'content': { 
    'foreign_id': 'tweet:34349698' 
  }, 
  // score between 0 and 100 indicating the importance of this event  
  // IE. a like is typically a more significant indicator than a click 
  'score': 2, 
  // (optional) the position in a list of activities 
  'position': 3, 
  // (optional) the feed the user is looking at 
  'feed_id': 'user:thierry', 
  // (optional) the location in your app. ie email, profile page etc 
  'location': 'profile_page' 
}; 
 
client.trackEngagement(engagement); 
client.trackEngagements([engagement1, engagement2])
```

gz#13226

**Comment by ferhatelmas** [comment]
It's a separate client hosted at https://github.com/getstream/stream-analytics-js
