### ISSUE TITLE
Support for Angular 11/12

### ISSUE THREAD

**Issue by Teacup5000** [GetStream/stream-js#476]
Hello,

I cannot get the getstream npm package to run in Angular 11/12:

`Error: node_modules/stream-chat/dist/types/client.d.ts:3:8 - error TS1259: Module '"xxx/node_modules/isomorphic-ws/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

3 import WebSocket from 'isomorphic-ws';
         ~~~~~~~~~

  node_modules/isomorphic-ws/index.d.ts:8:1
    8 export = WebSocket
      ~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSynth
eticDefaultImports' flag.

Error: node_modules/stream-chat/dist/types/connection.d.ts:3:8 - error TS1259: Module '"xxx/node_modules/isomorphic-ws/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

3 import WebSocket from 'isomorphic-ws';
         ~~~~~~~~~

  node_modules/isomorphic-ws/index.d.ts:8:1
    8 export = WebSocket
      ~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSynth
eticDefaultImports' flag.

Error: node_modules/stream-chat/dist/types/utils.d.ts:2:8 - error TS1259: Module '"xxx-
web/node_modules/stream-chat/node_modules/form-data/index"' can only be default-imported using the 'allowSyntheticDefaul
tImports' flag

2 import FormData from 'form-data';
         ~~~~~~~~

  node_modules/stream-chat/node_modules/form-data/index.d.ts:10:1
    10 export = FormData;
       ~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSynth
eticDefaultImports' flag.`

A similar ticket was closed: https://github.com/GetStream/stream-chat-js/issues/706

However, the proposed solution (upgrade of Typescript) does not work. I am using v4.2.3.

Before closing this ticket, please tell me if the getstream npm package works with Angular 11/12 at all.

**Comment by bityardigans** [comment]
"esModuleInterop": true appears to not work any longer

**Comment by mahboubii** [comment]
@bityardigans same as https://github.com/GetStream/stream-chat-js/issues/841#issuecomment-992920931

**Comment by gelinger777** [comment]
can somebody provide a really working example for Angular Apps (browser) using services? 

I am getting 
``` Generic type 'AxiosResponse<T>' requires between 0 and 1 type arguments.
[ng] 
[ng] 323     handleResponse: <T>(response: axios.AxiosResponse<T, any>) => T;
[ng]                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] 
``` 
when  I do 

```import { connect } from 'getstream';```
