### ISSUE TITLE
Maximum amount of activities I can read for a single feed via APIs ?

### ISSUE THREAD

**Issue by nattogo** [GetStream/stream-js#485]
**Maximum amount of activities I can read for a single feed via APIs ?**

I am using Getstream for my system and starting with the `Starter` plan.
When I read a feed from API, Getstream API only returns up to `500` latest activities. 
This number is too small to accept. I can't find any documentation from Getstream that mentions this problem.

You can check this repo to see my test results: [getstream-e2e](https://github.com/nattogo/getstream-e2e).

Thanks.

**Comment by ferhatelmas** [comment]
This is related to your plan and use-case, not the SDK so please contact to [support](https://getstream.io/contact/support/).

**Comment by nattogo** [comment]
> This is related to your plan and use-case, not the SDK so please contact to [support](https://getstream.io/contact/support/).

Thank you.
