### ISSUE TITLE
custom aggregation field is not working

### ISSUE THREAD

**Issue by faustoct** [GetStream/stream-js#496]
I'm trying to build aggregate field by custom field but it is not working it is adding as value of '' in group field. So my app is in production and I'm looking for a quickly workaround to apply if you guys have one.

**Comment by ferhatelmas** [comment]
could you write to support ? we need to see your app id/configuration and what you're trying to achieve. SDK issue isn't a good place to collect this information. Thanks for your collaboration.

**Comment by faustoct** [comment]
Already did it but it takes a day to have one reply it's not a kind of support i look for. Maybe the community can help with workaround.

**Comment by ferhatelmas** [comment]
> already did it but it takes a day to have one reply it's not a kind of support i look for

I didn't see this. Let me check and fasten if possible.

Stackoverflow is a good medium (I try to keep an eye on it too). Please try to give a detailed explanation of the problem. For example, your description above doesn't say much so hard to help even if somebody wants to do.
