### ISSUE TITLE
Enriched reactions

### ISSUE THREAD

**Issue by luantrasel** [GetStream/stream-js#503]
Hi there,

I'd like to know if getStream feeds support the enrichment of reactions, because I'd like to store references to objects like author inside the reaction and have it enriched automatically as I can do with activities.

I tried to store objects (created from collections.add) inside a reaction's data but I wasn't able because an error was thrown. So I'm not sure if this is an error, or if this is something that you don't support.

To store objects inside reactions I was doing this

```
const author = await client.collections.add('authors', null, { 
        name: 'Author',
    })

await client.reactions.add("comment", activity.id, { text: "nice post!", author }, { userId: user.id })
```

But then the following is error was being thrown

> Error: Converting circular structure to JSON
    --> starting at object with constructor 'StreamClient'
    |     property 'personalization' -> object with constructor 'Personalization'
    --- property 'client' closes the circle
    
Instead of adding the full author object to the reaction, I was able to add author.id and also author.data, but that way the object will not be enriched / updated once the author is updated

But first I'd need to know if getStream supports or not enriched reactions

I'm using latest version (8.0.0)

Thanks

**Comment by ferhatelmas** [comment]
Reactions requires an user and enriches it automatically, you don't need to add extra information.

```js
client.reactions.add(kind, activityID, data, { userId }); // where you can pass your author instead of userId
```

**Comment by ferhatelmas** [comment]
You want the actual user it seems, not the commenter. Then, isn't it the same with activity actor ?

**Comment by luantrasel** [comment]
@ferhatelmas first thanks for the information, I asked getStream support and they enabled it for me.

Maybe my example wasn't good, but yes, we need extra information on the reaction that also needs to be enriched automatically.

The problem is that I receive the following error when I try to add an reaction with the object from the collection within the data of the reaction.

> Error: Converting circular structure to JSON
--> starting at object with constructor 'StreamClient'
| property 'personalization' -> object with constructor 'Personalization'
--- property 'client' closes the circle

Piece of code where I add the reaction

```
const extraReactionInfo = await client.collections.add('extra-info', null, { 
        info: 'xxx',
})

// the error happens on the line below
await client.reactions.add("comment", activity.id, { text: "nice post!", extraReactionInfo }, { userId: user.id })
```

Am I adding the reaction correctly? Or how should I add an object (in this example extraReactionInfo) that needs to be enriched on the reaction?

**Comment by luantrasel** [comment]
@ferhatelmas it worked

I was trying to send the whole object because when I add this way on activities it works.

Thank you!

**Comment by ferhatelmas** [comment]
Great, let us know if you bump any issues and feedback for the SDK.

**Comment by MnsrIl** [comment]
Hi! I have similar case, but in my case I just trying to extend an reaction object with custom field, which will contain comment's image url. I tried this way to do that, but it doesn't work for me. 
````javascript
const reactionId = activityId || commentId;
const data = {
  text: "This is random comment",
  image_url: "https://ibb.co/mtLxLtH"
};
const commentCreatePromise = streamChatClient?.reactions.addChild('comment', reactionId, data, {
    userId: user?.id || '',
});
````
I still get the reaction with only text field. Is there any support for doing this?

The final reaction object, that I retrieved after that: 
````javascript
const finalData = {
  activity_id: "8bb824a0-bbf7-11ec-8080-80007eaeb9bf"
  children_counts: {}
  created_at: "2022-04-14T18:15:35.614903Z"
  data: {
    text: "image"
  }
  id: "1579eb98-00fc-44b7-9f63-a1baa9749c63"
  kind: "comment"
  latest_children: {}
  parent: ""
  updated_at: "2022-04-14T18:15:35.614903Z"
  user_id: "cl1b4600s06e009ma59cgggxo"
}
````

**Comment by ferhatelmas** [comment]
There is a problem in your example because you're calling `addChild` which means you're trying to add a comment to existing comment but `parent` of your response is empty so it's a comment on activity.  That's why that response isn't coming that request.

Problem is here:

> const reactionId = activityId || commentId;

if `activityId` exists you need to call `client.reactions.add`, otherwise call `client.reaction.addChild`.

Overall, you're adding custom data, not a reference and you don't want to enrich it. I believe, your issue is irrelevant to this ticket.

**Comment by ferhatelmas** [comment]
@AnnikaChauhan It's a flag in the server side (to enrich users in reaction data) that should be enabled for your app. Please contact to support to get it enabled (I am not in the company anymore).

**Comment by AnnikaChauhan** [comment]
@ferhatelmas thanks so much, I've raised this with them. Really appreciate your response despite not working at the company!
