### ISSUE TITLE
Block users?

### ISSUE THREAD

**Issue by CameronSilverTXI** [GetStream/stream-js#528]
Good afternoon.

We use Streams (feed and chat) for our platform, and found it to be quite excellent.

However we are getting a little pushback from the Google Play store about the inability to block users. Does Stream (feeds) offer any functionality for this? I looked through the docs (and code) to see if I could find anything, but came up short. We have a mobile app and web app, and feel that blocking is something that should be handled by the backend (rather than the client).

I know that users can be muted through the Chat client, but what about the feed client?

Did I miss anything??

Thanks!

**Comment by ferhatelmas** [comment]
Chat has also ban functionality, fyi.

For feeds, moderation capabilities are limited so you need to handle it through JWT.
Provide short lived expiration and stop giving new tokens to users if you don't want them to access anymore.

**Comment by CameronSilverTXI** [comment]
The issue we're facing is not about banning users from the platform, but rather giving the users the ability to block other users. For example, UserA blocks UserB, and no longer seen any of UserB's content. Ideally this will be handled by the Streams Feed backend (or client), so that we don't have to implement custom logic to web and mobile.

**Comment by ferhatelmas** [comment]
UserA can unfollow UserB feed to remove any unwanted content. Why doesn't it work?

**Comment by CameronSilverTXI** [comment]
Oh, yes of course! Forgive me for not realizing this, our platform does indeed surface some content from unfollowed users, which I know is not a standard way for using the feed client. We will work around this.

Thanks so much for the prompt and informative help!
