### ISSUE TITLE
Can't add reaction (like) "user_id is a required field"

### ISSUE THREAD

**Issue by monzersmiledev** [GetStream/stream-js#534]
![Annotation 2023-01-17 153449](https://user-images.githubusercontent.com/56754446/212912984-694b228c-8bb3-424b-aa94-d6f353a857da.png)

I'm trying to add a new reaction (like) i did pass the userId to the add function but i still get 

Error: 
```
{
"detail":"Errors for fields 'user_id'",
"status_code":400,
"code":4,
"exception":"InputException",
"exception_fields":{
"user_id":["user_id is a required field"]},
"duration":"0.18ms",
"more_info":"https://getstream.io/docs/api_error_responses"
}
```
 with HTTP status code 400

so i tried editing the package code as seen in the attached picture

i edited the body object userId property from

```
var body = {
        id: id,
        activity_id: activity instanceof Object ? activity.id : activity,
        kind: kind,
        data: data || {},
        target_feeds: this._convertTargetFeeds(targetFeeds),
        user_id: data.userId
      };
```

to:

```
var body = {
        id: id,
        activity_id: activity instanceof Object ? activity.id : activity,
        kind: kind,
        data: data || {},
        target_feeds: this._convertTargetFeeds(targetFeeds),
        user_id: data.userId
      };
```

and everything works fine after that

**Comment by ferhatelmas** [comment]
Where does the screenshot come from? If it's from this SDK, could you share link to source code ?
What is the version of SDK ?
Also, finally user & id is given to add as 4th parameters.
