### ISSUE TITLE
Package JSON is being bundled in the JavaScript dist code

### ISSUE THREAD

**Issue by Buzzertech** [GetStream/stream-js#549]
# Context

We have noticed that this library ships about 3kb of it's package.json content with it's [dist code](https://github.com/GetStream/stream-js/blob/3c3c3eeaa5b5fa4fa307dc79706da387b21bcd73/dist/js/getstream.js#L9819)

## Current behaviour 
The culprit seems to be this import inside [client.ts](https://github.com/GetStream/stream-js/blob/3c3c3eeaa5b5fa4fa307dc79706da387b21bcd73/src/client.ts#L33) where the `pkg` is being imported to retrieve the library version which is used [here](https://github.com/GetStream/stream-js/blob/3c3c3eeaa5b5fa4fa307dc79706da387b21bcd73/src/client.ts#L403).

## Expected behaviour
You could inject the version string at build time by using webpack's [DefinePlugin](https://webpack.js.org/plugins/define-plugin/).

**Comment by xernobyl** [comment]
Thank you for the input. We're deploying a fix.
