### ISSUE TITLE
Feature Request: Add support for arccos, arcsin, and arctan in Custom Rankings

### ISSUE THREAD

**Issue by asnaseer** [GetStream/stream-js#577]
Would it be possible for you to add support for `arccos`, `arcsin`, and `arctan` functions for Custom Ranking.

We have a use case where we want to rank bird sighting activities based on how far away the sighting was from the users home location. We know the longitude and latitude of the users home location as well as that of where the bird sighting took place. There is a well known formula for calculating the distance between to such points on the Earth given by:
```
d = 3963.0 * arccos[(sin(lat1) * sin(lat2)) + cos(lat1) * cos(lat2) * cos(long2 – long1)]
```
As you can see, it makes use of the `arccos` function that you do not currently seem to support.

I think this would be something that many other customers of yours will also find useful.

**Comment by xernobyl** [comment]
Feature was added to the backend. Should be deployed in the coming days.
