### ISSUE TITLE
Add support for retrieving activities by foreign id or uuid

### ISSUE THREAD

**Issue by ritesh-nitw** [GetStream/stream-js#70]
It would be great if activities can be retrieved using foreign id or uuid. 
Right now , filters available are:
limit	{int}	
id_gte	
id_gt	{int}
id_lte	
id_lt	{int}	
offset	

Would really like to have id_e filter. There are very few cases where this is required. 

Thanks

**Comment by ritesh-nitw** [comment]
Any chances of bringing-in this enhancement in future?

Thanks,
Ritesh

**Comment by tbarbugli** [comment]
we have plans to add this to Stream's API. once that's done we will shortly add the functionality to all clients as well.

**Comment by ritesh-nitw** [comment]
@tbarbugli : Hey Tom, Any hope that we can have this feature in near future! Retrieving one activity by criteria foreign id or uuid would make our life easier.

Thanks,
Ritesh

**Comment by jdkanani** [comment]
@tbarbugli Is this supported yet?

**Comment by monstrfolk** [comment]
please implement.

**Comment by tbarbugli** [comment]
retrieving 1 activity by id is already possible using `feed.get`

```js
feed.get({limit:1, id_lte: activityId});
```

**Comment by monstrfolk** [comment]
foreign id?

**Comment by blue4209211** [comment]
Hey Team,

Any plan for adding feed retrieval by foreignKey ??

**Comment by conary-h** [comment]
?
