### ISSUE TITLE
Uncaught ReferenceError: __jsonp3__ is not defined

### ISSUE THREAD

**Issue by sampeka** [GetStream/stream-js#72]
Getting thrown these two errors (together) from the front end client. I'm using google chrome, although seem to also get it from safari. 

```
Uncaught ReferenceError: __jsonp3__ is not defined 
faye.getstream.io/faye?message=%5B%7B%22channel%22%3A%22%2Fmeta%2Fconnect%2…%22%3A%22callback-polling%22%2C%22id%22%3A%224%22%7D%5D&jsonp=__jsonp3__:1 

getstream.js:4234 WebSocket is already in CLOSING or CLOSED state.
(anonymous function) @ getstream.js:4234
(anonymous function) @ getstream.js:2621
_invoke @ getstream.js:2297
(anonymous function) @ getstream.js:2290
onNextTick @ getstream.js:4697
Item.run @ getstream.js:178
drainQueue @ getstream.js:148
```

The WebSocket error seems to be recoverable and happens quite often, but the ReferenceError is a bit more a problem since it crashes hard and happens unpredictably. Any ideas what this could be?

**Comment by matthisk** [comment]
This has to do with the realtime subscription to feed changes managed by Faye. I will have to investigate why this problem is occurring, do you have any additional information on what you are trying to achieve when this problem occurs?

**Comment by sampeka** [comment]
I'm using the api to receive realtime updates from a notifications feed, here's an extract of the code I'm using (pretty much the same as what's in your docs):

    var client = stream.connect(NOTIFICATIONS.streamApiKey, null, NOTIFICATIONS.streamAppId);
    var user = client.feed('notification', NOTIFICATIONS.userId, NOTIFICATIONS.token);

    function success(data) {
        // ... does stuff
    }

    user.subscribe(success)

**Comment by matthisk** [comment]
You could try to debug the faye client that is used by our library to create subscriptions on realtime notifications. A call to ``feed.subscribe`` returns a promise object, can you make sure the Promise is not rejected with an error:

```js
user.subscribe(success).then(
    function () { /* succesfully created connection */ }, 
    function(err) { /* log error */ }
);
```

Otherwise the Faye [docs](http://faye.jcoglan.com/browser/subscribing.html) could also present a solution or clue why you get this problem.

Let me know if you find a fix, otherwise I will reach out to the people behind Faye to ask for help.

**Comment by bdmac** [comment]
We are seeing this error as well. It seems to happen after some relatively random length of time. For example if I leave a browser tab open with the console up and walk away for lunch, I will come back and generally the debugger will have stopped on this error happening. Note that I was not even at the computer so I did not change channels or subscriptions or anything.

**Comment by matthisk** [comment]
We are updating the Faye dependency to 1.1.2 in release 3.1.0, this should fix these Faye related errors. Please open a new issue if you are still seeing this exception after release 3.1.0

**Comment by bdmac** [comment]
@matthisk we are still seeing this issue with the updated Faye dependency in our app. I just left the debugger open for like an hour on one of our pages that is using the realtime subscriptions and hit this error again.

**Comment by benmgreene** [comment]
Yes, I'm seeing this too (using Meteor).

**Comment by beau6183** [comment]
Seeing this issue too.

**Comment by beau6183** [comment]
Thanks again for the help today!
