### ISSUE TITLE
[ReactNative] cant' find variable document

### ISSUE THREAD

**Issue by shprink** [GetStream/stream-js#77]
When running something like that to retrieve items:

```
this.user.get({limit: 5}).then(function(data) {
            var activities = data.results;
            console.log('activities', activities);
        }, function(reason) {
            console.log('reason', reason);
        });
```

I get "cant' find variable document" in the function `is_crossDomain`

I guess using getstream with ReactNative is not possible unfortunately.

PS: I bundle my app with Webpack

**Comment by tschellenbach** [comment]
Hi Julien,

I like your blog. Especially the post about Parse got a lot of attention. A blogpost about using Stream together with React Native would help a lot of people. Let's chat about it, my email is on my github profile.

Cheers,
Thierry

**Comment by shprink** [comment]
That's a good idea, I am also willing to open source the components that I will have to create.

My skype is: shprink

**Comment by matthisk** [comment]
Should be working in version 3.1.1 of the library
