### ISSUE TITLE
Feed wide read-only tokens

### ISSUE THREAD

**Issue by jacobwindsor** [GetStream/stream-js#79]
It seems to me that issuing read-only tokens on a feed specific basis is laborious and unnecessary. Currently, generating read-only tokens is a method of the feed object. Consider this example in python:

    feed = client.feed('user', user.id)
    return feed.get_read_only_token()

Now, shouldn't any user be able to read any users personal stream? So why the feed specific read-only token or even the need for a token at all? Would it not be simpler to avoid the need to create a token for each user feed?

    return get_read_only_token('user')

**Comment by tschellenbach** [comment]
so i think that is partially supported, @tbarbugli will know more

**Comment by tbarbugli** [comment]
creating tokens with read access for all feeds is not exposed by a public method and it's not the default behavior, we'll probably add a few helper functions in the future for that.

In the meantime this should works for your use-case:

```js
var streamSigner = require('getstream/src/lib/signing');
var apiSecret = '...';
streamSigner.JWTScopeToken(apiSecret, 'feed', 'read', {'feedId': '*'});
```

**Comment by jacobwindsor** [comment]
@tbarbugli Thanks for the solution

**Comment by jacobwindsor** [comment]
Sorry, to reopen this issue. I know I should have checked your solution worked before closing it @tbarbugli.

Anyway, it seems the token is not valid without specifying the feed ID:

    streamSigner.JWTScopeToken(apiSecret, 'feed', 'read', {'feedId': '*'}); # 403 error

    streamSigner.JWTScopeToken(apiSecret, 'feed', 'read', {'feedId': 'user2'}); # 200, okay

**Comment by tbarbugli** [comment]
looking into that
