### ISSUE TITLE
Add support for deleting activities from everywhere by foreign_id

### ISSUE THREAD

**Issue by ritesh-nitw** [GetStream/stream-js#80]
Will it be possible to add an api call for deleting activities by foreign_id from everywhere in the client similar to update call?

```
// send the update to the APIs
client.updateActivities([activity]);

//Something like
client.deleteActivities([activity]);
```

Thanks

**Comment by izakfilmalter** [comment]
This seems like a really basic ask. @tbarbugli, why was this closed? is there some other option for it?

**Comment by ferhatelmas** [comment]
An activity makes sense in a feed context so it can be removed from a feed and delete by `foreign_id` is supported.

**Comment by izakfilmalter** [comment]
@ferhatelmas The problem right now is you have to have the userId for the activity. It would be great to just need the `foreign_id` to delete it.

**Comment by ferhatelmas** [comment]
`user_id` is a convoluted vocabulary but it means the feed id. If feed structure is done well (with proper follows), removing it from the main source feed will delete from other feeds too.
