### ISSUE TITLE
Yarn support

### ISSUE THREAD

**Issue by zvictor** [GetStream/stream-js#98]
I am facing an issue that only appears when `getstream` is installed by **Yarn** (tried versions `0.17.10` and `0.18.1`). The same doesn't happen with **NPM**.

```
Uncaught TypeError: Cannot read property 'Context' of undefined
    at meteorInstall.node_modules.sshpk.lib.formats.x509.js (modules.js?hash=cbedf00…:97598)
    at meteorInstall.node_modules.sshpk.lib.certificate.js (modules.js?hash=cbedf00…:94227)
    at meteorInstall.node_modules.sshpk.lib.fingerprint.js (modules.js?hash=cbedf00…:93951)
```

I can see that it is related to the `sshpk` dependency.

**Comment by dwightgunning** [comment]
Apologies for the lack of communication around this issue. We're aiming to improve on this (in a big way).

On review of the linked issue, and in particular [this comment](https://github.com/yarnpkg/yarn/issues/2229#issuecomment-267756271) pointing to the bundler, it looks most likely that this was a problem Meteor.

I've just attempted to replicate this by following our Meteor blog post with a fresh Meteor install and Yarn v0.27.5; it runs through fine. This leads me to believe the bug has been resolved.

I'll close for now but happy to re-open / discuss further if appropriate.
