### ISSUE TITLE
CORS issue when using meteor

### ISSUE THREAD

**Issue by zvictor** [GetStream/stream-js#99]
I am following the documented steps for getting started and everything went well until the "[Retrieving Activities](https://getstream.io/docs/?language=js#retrieve)" step.

---

Running

```js
    import stream from 'getstream' // stream-js v3.5.0
    const client = stream.connect(APP_KEY, null, APP_ID, { location: 'eu-west' });
    const user1 = client.feed('user', '1', READ_ONLY_TOKEN);

    user1.get({ limit:5, offset:5 })
      .catch((errorData) => {
        console.log(errorData);
      });
```

gives me

```js
    {
        error: undefined,
        response: {
            statusCode: 0,
            request: {
                uri: {
                    protocol: "https:",
                    slashes: true,
                    auth: null,
                    host: "api.getstream.io",
                    port: null,
                    hostname: "api.getstream.io",
                    hash: null,
                    search: "?limit=5&offset=5&api_key=...secret...&location=unspecified",
                    query: "limit=5&offset=5&api_key=...secret...&location=unspecified",
                    pathname: "/api/v1.0/feed/global/global/",
                    path: "/api/v1.0/feed/global/global/?limit=5&offset=5&api_key=...secret...&location=unspecified",
                    href: "https://api.getstream.io/api/v1.0/feed/global/global/?limit=5&offset=5&api_key=...secret...&location=unspecified"
                },
                method: "GET",
                headers: {
                    stream - auth - type: "jwt",
                    Authorization: "...secret...",
                    ["X-Stream-Client"]: "stream-javascript-client-browser-unknown",
                    accept: "application/json"
                }
            }
        }
    }
```

----

Any suggestion of what I could try here?

**Comment by zvictor** [comment]
A deeper investigation in the Chrome DevTools allowed me to find CORS-related issues. That's the message I found:

> XMLHttpRequest cannot load https://eu-west-api.getstream.io/api/v1.0/feed/newsfeed/global/?limit=5&offset=0&api_key=...secret...&location=unspecified. Response to preflight request doesn't pass access control check: A wildcard `*` cannot be used in the `Access-Control-Allow-Origin` header when the credentials flag is true. Origin `http://localhost:3000` is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute.

----

I was not expecting to have an issue of this type since I am not making any request directly, but instead only using stream-js methods.

**Comment by zvictor** [comment]
I made a reproducible of this bug that you can find at https://github.com/zvictor/stream-bug. I hope it helps. As you can see, it is a Meteor application that intentionally does not make use of [stream-meteor](https://github.com/GetStream/stream-meteor).

**Comment by JelteF** [comment]
Thanks for the bug report an the repo. I can indeed reproduce the issue, but it's not immediately clear what is going wrong. `withCredentials` should to be set to false by https://github.com/matthisk/xmlhttp-request

After christmas I'll investigate further.

**Comment by JelteF** [comment]
I found out the problem. Meteor has its own browser fallback for the request lib that has a different default for withCredentials. This overrides the request browser library that I mentioned before. PR #100 should fix this by setting withCredentials explicitly.

**Comment by zvictor** [comment]
Awesome job! I can't wait to see it working in my app 🐣🎉🍻

**Comment by JelteF** [comment]
I merged it into master, you can use install from there for now until it is released.

**Comment by aldeed** [comment]
I ran into this, and installing from master fixes it, but it would help save some hunting time for others if you could publish the patch to NPM. Thanks

**Comment by yiziz** [comment]
I think I'm getting this issue, but I'm using webpack to compile a regular js app, not meteor.

<img width="1388" alt="screen shot 2017-10-26 at 5 11 37 pm" src="https://user-images.githubusercontent.com/1268502/32082761-ac58851e-ba72-11e7-97a9-4c5b2436bacc.png">
